### ISSUE TITLE
remove some useless configuration in settings.py

### ISSUE THREAD

**Issue by deming7h777** [NAL-i5K/general_issues#1]
There are some file have been removed but the configuration is still in settings.py.(ex. jquery-ui.js,...)
It may confuse someone who want to figure out the whole genomics-workspace.

**Comment by hsiaoyi0504** [comment]
@deming7h777 Can you elaborate a little bit ? It seems to me that `jquery-ui.js` is still useful.

**Comment by deming7h777** [comment]
I can't find the jquery-ui.js in blast/script directory and even all of the repo

**Comment by hsiaoyi0504** [comment]
It's because it's installed by webpack: https://github.com/NAL-i5K/genomics-workspace/blob/84ec7d6901227dfe8dce8babf863eef31cc5c09c/webpack.config.js#L57.

**Comment by deming7h777** [comment]
I have seen that, i mean i don't find any script or html import jquery-ui.js

**Comment by hsiaoyi0504** [comment]
BTW, this perhaps is a good alternative of **django-pipeline**: https://django-compressor.readthedocs.io/en/latest/. One important feature attracts me is that 

> **JS/CSS belong in the templates**
Every static combiner for Django I’ve seen makes you configure your static files in your settings.py. While that works, it doesn’t make sense. Static files are for display. And it’s not even an option if your settings are in completely different repositories and use different deploy processes from the templates that depend on them. - django-compressor

**Comment by deming7h777** [comment]
thanks for reminding !

**Comment by childers** [comment]
Issue moved to [NAL-i5K/genomics-workspace #245](https://github.com/NAL-i5K/genomics-workspace/issues/245) via [**ZenHub**](https://www.zenhub.com/)
