### ISSUE TITLE
Apollo2.6.0 update to use new CSS

### ISSUE THREAD

**Issue by childers** [NAL-i5K/general_issues#107]
The update to Apollo2.6.0 and more modern JBrowse has required us to update our CSS. 

Instead of loading this as a plugin, the JBrowse and Apollo developers suggested I have the CSS in a common location that all the species can load, so it is in one place. 
This is available  on apollo-dev: /app/data/other_species/vardes/Vdes_3.0/jbrowse/data/custom.css 

- [ ] I also need to update our version in source control

**Comment by mpoelchau** [comment]
@childers can this be closed?
