### ISSUE TITLE
account to access genomics-workspace admin UI needed on i5k-dev 

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#113]
We'll need to create an admin account on i5k-dev to access the administrative functions on the UI.

**Comment by g8tor** [comment]
Starting work on this issue now. @childers do you need this as well or did we already do this?

**Comment by mpoelchau** [comment]
I tried the new login and got a 500 error.

**Comment by mpoelchau** [comment]
It works now - thank you @g8tor!
