### ISSUE TITLE
Genomics-workspace 502 errors on i5k-dev 

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#114]
We occasionally (but not always) get 502 errors for the genomics-workspace pages. 

![Screen Shot 2020-08-19 at 12 49 43 PM](https://user-images.githubusercontent.com/5487172/90677344-7cdb5f00-e21a-11ea-8063-d78053bf5894.png)

**Comment by g8tor** [comment]
@mpoelchau can you be more descriptive at to nwhen this is happening? Thanks

**Comment by mpoelchau** [comment]
For me it is browser-dependent, but I don't know why (e.g. browser vs. history vs. something else). I believe @childers also gets this error.

See screenshot - Chrome at the top, safari in the middle, firefox at bottom

![Screen Shot 2020-08-24 at 7 50 13 AM](https://user-images.githubusercontent.com/5487172/91052284-795f2380-e5de-11ea-8e8f-d50219e5e2e6.png)

**Comment by g8tor** [comment]
@mpoelchau I have tried it with all three browsers I have installed and can't reproduce this error at the moment.
<img width="1123" alt="Screen Shot 2020-08-25 at 8 22 38 AM" src="https://user-images.githubusercontent.com/123337/91173748-513df600-e6ac-11ea-9d20-218502a2dbad.png">

**Comment by mpoelchau** [comment]
Thanks @g8tor , looks like this is fixed!
