### ISSUE TITLE
'Jbrowse settings' is not in genomics-workspace admin menu on i5k-dev 

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#117]
On our production site, we have a Jbrowse settings admin function:

![Screen Shot 2020-08-25 at 8 16 43 AM](https://user-images.githubusercontent.com/5487172/91185888-957cc680-e6ab-11ea-8570-14bf0c19ca29.png)

This is not shown on i5k-dev:

![Screen Shot 2020-08-25 at 8 15 37 AM](https://user-images.githubusercontent.com/5487172/91185774-75e59e00-e6ab-11ea-847d-83e2bef58df7.png)

**Comment by childers** [comment]
There is a JBROWSE setting in the config that can be true or false.  I wonder if this setting got lost or mis-set at some point?

**Comment by childers** [comment]
Actually, this is set to false in the settings file!
```ENABLE_JBROWSE_INTEGRATION = False

# customize some part of django-suit settings based on ENABLE_JBROWSE_INTEGRATION
if ENABLE_JBROWSE_INTEGRATION:
    blast_models = (
            {'model': 'blastqueryrecord'},
            {'model': 'sequencetype'},
            {'model': 'blastdb'},
            {'model': 'jbrowsesetting'},  # only exsit when ENABLE_JBROWSE_INTEGRATION == True
            {'model': 'sequence'},
    )
```

**Comment by childers** [comment]
I will set this to TRUE and we'll see if it helps.

**Comment by mpoelchau** [comment]
@childers do we need to re-deploy in order to see the change?

**Comment by mpoelchau** [comment]
It's working now. Thanks @g8tor !
