### ISSUE TITLE
the i5k_features module breaks migrating to tripal 3

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#12]
The `i5k_features` module hard-loads a tripal 2 file based on relative path, which breaks the upgrade from tripal 2 to 3.  (error below)

`require_once (dirname(__FILE__).'/../../contrib/tripal/tripal_core/includes/tripal_core.toc.inc');`

easy to resolve by disabling the module prior to beginning the migration process, but i am making an issue to remember to fix the path if we do need to re-enable the module.  https://github.com/tripal/tripal/blob/7.x-3.x/legacy/tripal_core/includes/tripal_core.toc.inc
IE `tripal/tripal_core/` to `tripal/legacy/tripal_core`

```
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/sites/all/modules/custom/i5k_features/../../contrib/tripal/tripal_core/includes/tripal_core.toc.inc' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/sites/all/modules/custom/i5k_features/i5k_features.module on line 8
Drush command terminated abnormally due to an unrecoverable error.                                     [error]
Error: require_once(): Failed opening required
'/var/www/html/sites/all/modules/custom/i5k_features/../../contrib/tripal/tripal_core/includes/tripal_core.toc.inc'
(include_path='.:/usr/share/pear:/usr/share/php') in
/var/www/html/sites/all/modules/custom/i5k_features/i5k_features.module, line 8
```

**Comment by bradfordcondon** [comment]
made a PR to the new_theme branch.  If thats not what i should do, let me know.

https://github.com/isdapps/i5k-tripal/pull/85

**Comment by mpoelchau** [comment]
Merged the PR.
