### ISSUE TITLE
apollo2 common names need spaces to be replaces with underscores

### ISSUE THREAD

**Issue by childers** [NAL-i5K/general_issues#121]
This needs to be changes in four places

1. the apollo2 database needs the common_name field so that %20 is replaced with _  in the "organism" table.

1. the genomics workspace blast_jbrowsesetting table needs the link updated to replace %20 with _ in the 'url' column.

1. the CWL or other workflows need to be changed in the setup for the BLAST and Apollo2 common name fields (need more info on this)

1. The tripal gene page linkouts need to replace %20 with _ (https://github.com/isdapps/i5k-tripal/blob/5d367b77519d2edc2c767033e077c5c98411dac8/sites/all/modules/custom/i5k_features/theme/templates/tripal_feature_base.tpl.php#L311 )

**Comment by g8tor** [comment]
All I can't (and havent been able to since yesterday) get on the arsnet vpn and when I try the arsnet1 connection I can connect but can't get to github or anythng for that matter. Still working on it

**Comment by g8tor** [comment]
- the apollo2 database common_name field has been updated
- the genomics workspace blast_jbrowsesetting  url firld has been updated

**Comment by mpoelchau** [comment]
I created a PR for the CWL issue but still need to test it: https://github.com/NAL-i5K/Organism_Onboarding/pull/104

Will close this after testing.

**Comment by mpoelchau** [comment]
Finished, closing.
