### ISSUE TITLE
Can't add annotations on apollo2-dev

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#123]
I did a number of tests on Apollo2 functionality, and a number of functions aren't working (see list below). The most obvious issue is that you can't add annotations. The common theme for these errors appears to be the Apollo2 web services.

Some colleagues have similar problems (couldn't add annotations), this comment on what they did to fix things might be a place to start: 
"I changed the Apache reverse-proxy configuration because I have the feeling that the proxying of browser websocket request from SSL enabled frontend server to Tomcat backend without SSL seems to be rejected by Tomcat."

Apollo documentation that might help: https://genomearchitect.readthedocs.io/en/latest/Configure.html?highlight=websocket#if-tomcat-is-running-ssl

The following doesn't work: 
- Ref Sequence tab in admin panel won't load sequences (403 error)
- Double-clicking on an organism on the 'Organism' tab leads to an indefinite 'Loading...' button
- can't add annotations
- can't create genomic insertions etc
- view in annotator panel function doesn't work
- GO linkout doesn't work (400)
- for existing annotations in the UcA track, adding comments doesn't work (will change in editor but won't save)
- for existing annotations in the UcA track, changing name doesn't work(will change in editor but won't save)
- for existing annotations in the UcA track, status update doesn't work (will change in editor but won't save)

Just as an FYI, in case it helps for debugging the following does work: 
- admin panel: updating user info in 'Users' tab
- admin panel: create new user
- reports (well same stuff is broken as it is on prod)
- tracks

I did not test the following yet:
- changing group values
- adding content via web services

**Comment by childers** [comment]
FYI: here is a screenshot of some of the websocket errors:

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/421248/93780240-e83b9680-fbf5-11ea-86bd-2afb6a9ac770.png">

**Comment by g8tor** [comment]
@mpoelchau and @childers  I want to close this issue based on the reasoning for https://github.com/NAL-i5K/general_issues/issues/122. Please test, confirm that the application(s) are behaving as expected.

Thanks

**Comment by mpoelchau** [comment]
Thanks @g8tor ! I tested all the above, the Apollo2 functions work now!
