### ISSUE TITLE
FASTA/GFF Upload Issue - Server path

### ISSUE THREAD

**Issue by Ferrisx4** [NAL-i5K/general_issues#125]
When using the FASTA/GFF loader, the "Server path" function is not able to access the file even if the file is owned by the webserver user and is completely readable by all users.

This may be related to #124 

![Screen Shot 2020-09-09 at 3 21 18 PM](https://user-images.githubusercontent.com/9593623/92643676-2a88dd80-f2b0-11ea-8343-58de5f34fcf9.png)

Possibilities:
 - file must be local to somewhere within the Drupal directory.
 - file is too large and the wrong error message is being displayed.

**Comment by mpoelchau** [comment]
@Ferrisx4 is this issue still current?
