### ISSUE TITLE
Need cron job to remove genomics-workspace tasks after 7 days

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#128]
We'll need to clear the filesystem, and discuss whether the db should also be cleared.

**Comment by g8tor** [comment]
Added the following cron jobs to my vernon.chapman.admin crontab to test on i5k-dev
55 00 * * * sudo find /usr/local/{i5k,i5k-training}/media/{blast,clustal,hmmer}/task -mtime +5  ! -path "*git*" ! -path "*/task" -exec rm -rf "{}" \;
40 00 * * * sudo find /usr/local/{i5k,i5k-training}/media/{blast,clustal,hmmer}/task -mtime +5 -type d ! -path '*/task' -exec rm -rf "{}" \;

Recieved Confimation emails for each minutes later

Will test in middle of the day tomorrow on staging

**Comment by mpoelchau** [comment]
We decided to clear the entries from the database, as well. @g8tor also brought up that we may want to collect some of the info from the json files and compile them as metrics, and he knows of some smart ways to do this.

**Comment by g8tor** [comment]
@mpoelchau  and @childers 

I'm going to close this issue and https://github.com/NAL-i5K/general_issues/issues/129 based on the below:

Finally Fixed issue that had cron failing. I updated the resultscleanup management command (in the cron branch).  
I scheduled a job for 10:30 AM and below are the confimation emails I recieved for both:

**i5k-training@nal.usda.gov**
Fri 10/2/2020 10:30 AM
Started processing BlastQueryRecord Objects at 14:30:03
No matching BlastQueryRecord objects located
Ended processing BlastQueryRecord Objects at 14:30:03

Started processing ClustalQueryRecord Objects at 14:30:03
No matching ClustalQueryRecord objects located
Ended processing ClustalQueryRecord Objects at 14:30:03

Started processing HmmerQueryRecord Objects at 14:30:03
No matching HmmerQueryRecord objects located
Ended processing HmmerQueryRecord Objects at 14:30:03

Total Records: 0
Total Elapsed Time: 0:00:00


**i5k@nal.usda.gov**
Fri 10/2/2020 10:30 AM
Started processing BlastQueryRecord Objects at 14:30:03
No matching BlastQueryRecord objects located
Ended processing BlastQueryRecord Objects at 14:30:03

Started processing ClustalQueryRecord Objects at 14:30:03
No matching ClustalQueryRecord objects located
Ended processing ClustalQueryRecord Objects at 14:30:03

Started processing HmmerQueryRecord Objects at 14:30:03
No matching HmmerQueryRecord objects located
Ended processing HmmerQueryRecord Objects at 14:30:03

Total Records: 0
Total Elapsed Time: 0:00:00
