### ISSUE TITLE
T3 species glossary tweaks

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#132]
URL: https://i5k.midspin.net/t3_species_glossary

- [x] Only published organisms should be listed
- [x] change header from 'Organism overview (Tripal 3)' to 'Species Overview'

**Comment by Ferrisx4** [comment]
Organism Overview (Tripal 3) is gone, replaced by 'Species Overview': https://github.com/NAL-i5K/t3_species_glossary/issues/3

**Comment by Ferrisx4** [comment]
Hiding unpublished organisms is the default functionality, we just had every organism published (by-product of the migration or testing phase).
I think we can close this for now unless there are more features we'd like to add. At some point, I would like to enable the [A-Z index feature](https://github.com/NAL-i5K/t3_species_glossary/issues/1) that existed on the Tripal 2 version of this page.
