### ISSUE TITLE
Install https://github.com/statonlab/feature_obliviator or ask to make it part of tripal core

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#133]
It looks like Tripal3 doesn't have the ability to delete features baked in (unlike tripal2). In snooping around Meg's repos I found this: 
https://github.com/statonlab/feature_obliviator

We should 1) install it and 2) figure out why this isn't part of Tripal core.

**Comment by mpoelchau** [comment]
Update: the devs say it's not part of Tripal core because it doesn't have a front end UI yet.

**Comment by Ferrisx4** [comment]
At least partial delete functionality (on Chado level) has been implemented in a recent pull request: https://github.com/tripal/tripal/pull/1061

**Comment by mpoelchau** [comment]
Let's take this off the table for now.
