### ISSUE TITLE
Correct formatting in transcripts table on Tripal3 gene page

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#138]
The values in the transcripts table are too close together.
A good multi-isoform example: https://i5k.midspin.net/bio_data/194986

@Ferrisx4 commented: This styling is being pulled from https://github.com/tripal/tripal/blob/7.x-3.x/legacy/tripal_core/theme/css/tripal_core.css#L135 which may need a fix. Alternatively, we can provide our own CSS class for this field, and then specify it somewhere in one of the i5k-specifc themes

**Comment by Ferrisx4** [comment]
In the "new" theme, at least on the Canton Group test site, this formatting issue no longer persists.

There is, however, a somewhat non-Drupal looking table instead.

**Comment by mpoelchau** [comment]
This has been superseded by the new transcripts view in Tripal 3.5 - closing.
