### ISSUE TITLE
Link-outs to cross references in Tripal3

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#139]
This is a placeholder issue that I'll add more info to.

**Comment by mpoelchau** [comment]
Looks like we'll need to update the URL prefix via raw sql. Yay. example db prefix for GeneID:https://www.ncbi.nlm.nih.gov/gene/{accession}

Let's do this after the migration.

**Comment by Ferrisx4** [comment]
The GUI to replace/update the Database prefix and URL works after a patch is applied, per the standard Tripal 3 installation (not-migration) [documentation](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/manual_install/install_tripal.html#apply-patches).  This allows us to avoid the raw SQL approach, however using SQL may still be valid if we want to script this.
