### ISSUE TITLE
remove comments that are spam

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#14]
most (all?) comments are spam?  So we should remove, and or be very careful to not display comments on new tripal sites.

**Comment by mpoelchau** [comment]
- [ ] delete all comments on live site via admin/content/comment/approval
- [ ] change all pages where comments are open to comments closed
- [ ] fix new page templates where comments were turned on by default - make closed by default (admin/structure/types)

**Comment by mpoelchau** [comment]
Closing - this should be taken care of when all T2 content has been removed from T3 site.
