### ISSUE TITLE
Update bundle types for existing analyses

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#140]
In our T2 content ingest we never specified what 'type' our analyses were - e.g. 'genome assembly' or 'genome annotation'.

In our T3 data ingest we will begin specifying these bundle types. 

It would be great if we could update the old analyses with bundle types, so that everything's consistent. I'm not sure how to do this in a way that's not manual.

**Comment by mpoelchau** [comment]
We need to discuss this some more with Meg to decide the best way to add the 'genome annotation' and 'genome assembly' analysis props.

**Comment by mpoelchau** [comment]
Meg suggests using the Tripal alchemist module with the manual conversion methods: https://github.com/statonlab/tripal_alchemist

**Comment by Ferrisx4** [comment]
Tripal Alchemist works flawlessly. Adding this step to Post Migration step for migration.
