### ISSUE TITLE
Fix Tripal3 Sample display

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#141]
The tripal3 sample data type looks pretty awkward right now: https://i5k.midspin.net/bio_data/252523. @Ferrisx4 do we need to update this manually post-migration?  What's the best way to handle this? 

<img width="324" alt="Screen Shot 2020-10-01 at 7 31 53 AM" src="https://user-images.githubusercontent.com/5487172/94815926-529fc400-03b8-11eb-8a07-64b938113883.png">

**Comment by Ferrisx4** [comment]
For the simple issue of getting the display to _look decent_, simply resetting the Display to the Default Tripal Layout will suffice. This fix also needs to be applied to the **Project** content type. ![Screen Shot 2020-10-15 at 11.20.40 AM.png](https://images.zenhubusercontent.com/5d3b0f16222f9f2d410cb70e/af334b20-13f6-44af-8e75-c0ff2850d35f)
Following this reset, we need to manually go into the Field settings and enable/disable/organize the fields as we see fit. This process is also being incorporated into the i5k Tripal 2 to Tripal 3 migration process: https://github.com/Ferrisx4/T2-T3_Ferris-Saga/blob/master/Saga_Condensed.md#5-post-migration-steps

<hr>

Currently, there seems to be an issue specifically related to Sample where data that is in the database, pulled in by Tripal EUtils, is not being shown on the content page, even if all fields are enabled.

**Comment by Ferrisx4** [comment]
Upon further review, it seems like although the data seems to exist in the database and additional Biosamples were loaded via the Tripal Eutils module, there is an issue when displaying this content type. Upon first page load, the additional categories (Properties, Cross Reference, Relationship) show up on the left, but promptly disappear before the page finishes loading followed by an error on the bottom of the page. PHP/webserver logs have so far been unhelpful. This does not seem to be an issue with other content types.

One of the fields may be malfunctioning, testing them currently.

**Comment by Ferrisx4** [comment]
After disabling all fields and re-enabling them one-by-one until they were all enabled, the pages appear to display correctly with almost all information.

While it does link properly to the associated Organism, it does not link to the associated Analysis.

**Comment by Ferrisx4** [comment]
We do not expect Biosamples to link to Analysis at the current time due to complexity in linking them:
 - [Mage Module](http://gmod.org/wiki/Chado_Mage_Module)
 - [EUtils 'Undecided Mappings'](https://tripal-eutils.readthedocs.io/en/latest/database_info/biosample.html)
