### ISSUE TITLE
Compare Blast2GO and GOanna GO terms

### ISSUE THREAD

**Issue by suryasaha** [NAL-i5K/general_issues#147]
# 11 genome i5k set and Dmel

- [ ] Latrodectus hesperus LHES spider
- [ ] Limnephilus lunatus LLUN caddisfly
- [ ] Oncopeltus fasciatus ONCFAS milkweed bug
- [ ] Homalodisca vitripennis HVIT leafhopper
- [ ] Eurytemora affinis EAFF copepod
- [ ] Agrilus planipennis APLA beetle
- [ ] Copidosoma floridanum CFLO wasp
- [ ] Athalia rosae AROS hymenoptera (bees)
- [ ] Ceratitis capitata CCAP diptera (flies)
- [ ] Cimex lectularius CLEC hemiptera (bugs)
- [ ] Varroa destructor VDES mite
- [ ] Drosophila 
- [ ] Honeybee
- [ ] Asian citrus psyllid D citri
- [ ] Triboleum castaneum beetle
- [ ] Clitarchus hookeri stick insect
- [ ] medauroidea extradentata Vietnamese or Annam walking stick

**Comment by suryasaha** [comment]
Need to convert Blast2GO GAF2 files into legal GAF2 files

**Comment by mpoelchau** [comment]
I believe this was handled during the paper writeup.
