### ISSUE TITLE
Generate GOanna v2.2 GO terms for all i5k organisms by Sept 2022

### ISSUE THREAD

**Issue by suryasaha** [NAL-i5K/general_issues#149]
Species to process (Species, assembly accession number, protein fasta location). If protein location fasta is 'refseq', 1. do first, 2. use NCBI datasets to get fasta file 

Datasets URL: https://www.ncbi.nlm.nih.gov/datasets/docs/v1/quickstarts/command-line-tools/
Example command: `./datasets download genome accession GCF_000002195.4 --filename test.zip --exclude-gff3  --exclude-seq --exclude-genomic-cds --exclude-rna`
The list below as a spreadsheet: [functional_annotation_list.xlsx](https://github.com/NAL-i5K/general_issues/files/7522113/functional_annotation_list.xlsx)

- [x] Aethina_tumida,GCF_001937115.1,refseq
- [x] Amyelois_transitella,GCF_001186105.1,refseq
- [x] Bactrocera_cucurbitae,GCF_000806345.1,refseq
- [x] Bactrocera_dorsalis,GCF_000789215.1,refseq
- [x] Bactrocera_oleae,GCF_001188975.1,refseq
- [x] Bemisia_tabaci,GCF_001854935.1,refseq
- [x] Bombus_impatiens,GCF_000188095.2,refseq
- [x] Bombus_terrestris,GCF_000214255.1,refseq
- [x] Cephus_cinctus,GCF_000341935.1,refseq
- [x] Chelonus_insularis,GCF_013357705.1,refseq
- [x] Contarinia_nasturtii,GCF_009176525.2,refseq
- [x] Diachasma_alloeum,GCF_001412515.1,refseq
- [x] Diaphorina_citri,GCF_000475195.1,refseq
- [x] Drosophila_biarmipes,GCF_018148935.1,refseq
- [x] Drosophila_bipectinata,GCF_018153845.1,refseq
- [x] Drosophila_ficusphila,GCF_018152265.1,refseq
- [x] Drosophila_rhopaloa,GCF_018152115.1,refseq
- [x] Drosophila_takahashii,GCF_018152695.1,refseq
- [x] Dufourea_novaeangliae,GCF_001272555.1,refseq
- [x] Eufriesea_mexicana,GCF_001483705.1,refseq
- [x] Fopius_arisanus,GCF_000806365.1,refseq
- [x] Galleria_mellonella,GCF_003640425.2,refseq
- [x] Habropoda_laboriosa,GCF_001263275.1,refseq
- [x] Leptinotarsa_decemlineata,GCF_000500325.1,refseq
- [x] Megachile_rotundata,GCF_000220905.1,refseq
- [x] Microplitis_demolitor,GCF_000572035.2,refseq
- [x] Neodiprion_lecontei,GCF_001263575.1,refseq
- [x] Nicrophorus_vespilloides,GCF_001412225.1,refseq
- [x] Nylanderia_fulva,GCF_005281655.1,refseq
- [x] Odontomachus_brunneus,GCF_010583005.1,refseq
- [x] Osmia_lignaria,GCF_012274295.1,refseq
- [x] Tribolium_madens,GCF_015345945.1,refseq
- [x] Varroa_jacobsoni,GCF_002532875.1,refseq
- [x] Trichogramma_pretiosum,BCM,https://i5k.nal.usda.gov/data/Arthropoda/tripre-(Trichogramma_pretiosum)/Current Genome Assembly/2.Official or Primary Gene Set/BCM_version_0.5.3/consensus_gene_set/TPRE.faa.gz
- [x] Tigriopus_californicus,TCALIF_genome_v1.0,https://i5k.nal.usda.gov/data/Arthropoda/tigcal-(Tigriopus_californicus)/Current Genome Assembly/2.Official or Primary Gene Set/TCALIF_v1.0/TCALIF_proteins_v1.0.fasta
- [x] Parasteatoda_tepidariorum,BCM,https://i5k.nal.usda.gov/data/Arthropoda/partep-(Parasteatoda_tepidariorum)/Current Genome Assembly/2.Official or Primary Gene Set/Augustus_gene_set-Primary_Gene_Set/aug3.1.aa.gz
- [x] Pachypsylla_venusta,BCM,https://i5k.nal.usda.gov/data/Arthropoda/pacven-(Pachypsylla_venusta)/Current Genome Assembly/2.Official or Primary Gene Set/BCM_version_0.5.3/consensus_gene_set/PVEN.faa.gz
- [x] Orussus_abietinus,BCM,https://i5k.nal.usda.gov/data/Arthropoda/oruabi-(Orussus_abietinus)/Current Genome Assembly/2.Official or Primary Gene Set/oruabi_OGS_v1.0/ORUABI_OGSv1-0_peptide.fa
- [x] Onthophagus_taurus,BCM,https://i5k.nal.usda.gov/data/Arthropoda/onttau-(Onthophagus_taurus)/Current Genome Assembly/2.Official or Primary Gene Set/BCM_version_0.5.3/consensus_gene_set/OTAU.faa
- [x] Melipona_quadrifasciata,GCA_001276565.1,https://i5k.nal.usda.gov/data/Arthropoda/melqua-(Melipona_quadrifasciata)/Current Genome Assembly/2.Official or Primary Gene Set/ASM127656v1_GenBank_annotations/GCA_001276565.1_ASM127656v1_protein.faa
- [x] Medauroidea_extradentata,GCA_003012365.1,https://i5k.nal.usda.gov/data/Arthropoda/medext-(Medauroidea_extradentata)/Current Genome Assembly/2.Official or Primary Gene Set/Mext_OGS_v1.0/Mext_OGS_v1.0_pep.fa.gz
- [x] Mayetiola_destructor,GCA_000149185.1,https://i5k.nal.usda.gov/data/Arthropoda/maydes-(Mayetiola_destructor)/Current Genome Assembly/2.Official or Primary Gene Set/OGS1.0/hf_OGS1.0.pep.fasta
- [x] Manduca_sexta,GCA_000262585.1,https://i5k.nal.usda.gov/data/Arthropoda/mansex-%28Manduca_sexta%29/JHU_Msex_v1.0/2.Official%20or%20Primary%20Gene%20Set/Manduca_sexta_Annotation_Release_102/GCF_014839805.1_JHU_Msex_v1.0_translated_cds.faa
- [x] Loxosceles_reclusa,BCM,https://i5k.nal.usda.gov/data/Arthropoda/loxrec-(Loxosceles_reclusa)/Current Genome Assembly/2.Official or Primary Gene Set/BCM_version_0.5.3/consensus_gene_set/LREC.Models_GCA_001188405.1_pep.fa
- [x] Locusta_migratoria,DAZY00000000,https://i5k.nal.usda.gov/data/Arthropoda/locmig-(Locusta_migratoria)/Current Genome Assembly/2.Official or Primary Gene Set/JAMg_OGSv1/locust.OGS_preQC.gff3.pep.gz
- [x] Lasioglossum_albipes,GCA_000346575.1,https://i5k.nal.usda.gov/data/Arthropoda/lasalb-(Lasioglossum_albipes)/Current Genome Assembly/2.Official or Primary Gene Set/Lalb_OGSv5.42/original_files/Lalb_OGS_v5.42.pep.fa
- [x] Laodelphax_striatellus,GCA_003335185.2,https://i5k.nal.usda.gov/data/Arthropoda/laostr-(Laodelphax_striatellus)/Current Genome Assembly/2.Official or Primary Gene Set/laostr_OGSv1.2/laostr_OGSv1.2_pep.faa
- [x] Ladona_fulva,GCA_000376725.2,https://i5k.nal.usda.gov/data/Arthropoda/ladful-(Ladona_fulva)/Current Genome Assembly/2.Official or Primary Gene Set/BCM_version_0.5.3/consensus_gene_set/LFUL.faa.gz
- [x] Hyalella_azteca,GCA_000764305.3,https://i5k.nal.usda.gov/data/Arthropoda/hyaazt-(Hyalella_azteca)/Current Genome Assembly/2.Official or Primary Gene Set/hyaazt_OGSv1.2/hyaazt_OGSv1.2_pep.fa
- [x] Holacanthella_duospinosa,GCA_002738285.1,https://i5k.nal.usda.gov/data/Arthropoda/holduo-(Holacanthella_duospinosa)/Current Genome Assembly/2.Official or Primary Gene Set/Holacanthella_duospinosa_annotation/Holacanthella_duospinosa_annotation_1.0_pep.fa.gz
- [x] Heliothis_virescens,GCA_002382865.1,https://i5k.nal.usda.gov/data/Arthropoda/helvir-(Heliothis_virescens)/Current Genome Assembly/2.Official or Primary Gene Set/H_virescens_OGS1/GCA_002382865.1_K63_refined_pacbio_protein.faa.gz
- [x] Halyomorpha_halys,GCA_000696795.3,https://i5k.nal.usda.gov/data/Arthropoda/halhal-(Halyomorpha_halys)/Current Genome Assembly/2.Official or Primary Gene Set/halhal_OGSv1.2/halhal_OGSv1.2_pep.fa
- [x] Gerris_buenoi,BCM,https://i5k.nal.usda.gov/data/Arthropoda/gerbue-(Gerris_buenoi)/Current Genome Assembly/2.Official or Primary Gene Set/gerbue_OGSv1.1/gerbue_OGSv1.1_pep.fa
- [x] Frankliniella_occidentalis,GCA_000697945.4,https://i5k.nal.usda.gov/data/Arthropoda/fraocc-(Frankliniella_occidentalis)/Current Genome Assembly/2.Official or Primary Gene Set/fraocc_OGSv1.1/fraocc_OGSv1.1_pep.fa
- [x] Euglossa_dilemma,GCA_002201625.1,https://i5k.nal.usda.gov/data/Arthropoda/eugdil-(Euglossa_dilemma)/Current Genome Assembly/2.Official or Primary Gene Set/GeneSet_v1-0/Edil_v1.0_peptide.fa.gz
- [x] Ephemera_danica,GCA_000507165.2,https://i5k.nal.usda.gov/data/Arthropoda/ephdan-(Ephemera_danica)/Current Genome Assembly/2.Official or Primary Gene Set/ephdan_OGSv1.0/ephdan_OGSv1.0_pep.fa
- [x] Clitarchus_hookeri,GCA_002778355.1,https://i5k.nal.usda.gov/data/Arthropoda/clihoo-(Clitarchus_hookeri)/Current Genome Assembly/2.Official or Primary Gene Set/Clitarchus_hookeri_annotation/Clitarchus_hookeri_Maker_annotations_pep.fa.gz
- [x] Centruroides_sculpturatus,BCM,https://i5k.nal.usda.gov/data/Arthropoda/censcu-(Centruroides_sculpturatus)/Current Genome Assembly/2.Official or Primary Gene Set/BCM_version_0.5.3/consensus_gene_set/CSCU.faa
- [x] Catajapyx_aquilonaris,BCM,https://i5k.nal.usda.gov/data/Arthropoda/cataqu-(Catajapyx_aquilonaris)/Current Genome Assembly/2.Official or Primary Gene Set/BCM_version_0.5.3/consensus_gene_set/CAQU.faa.gz
- [x] Blattella_germanica,BCM,https://i5k.nal.usda.gov/data/Arthropoda/blager-(Blattella_germanica)/Current Genome Assembly/2.Official or Primary Gene Set/blager_OGS_v1.0/BGER_OGSv1-0_pep.fa
- [x] Anoplophora_glabripennis,BCM,https://i5k.nal.usda.gov/data/Arthropoda/anogla-(Anoplophora_glabripennis)/Current Genome Assembly/2.Official or Primary Gene Set/OGS_v1_2/agla_OGS_v1_2_peptide.fa

**Comment by amcooksey** [comment]
Completed 
Aethina tumida
Amyelois transitella
[functional_annotation_list.xlsx](https://github.com/NAL-i5K/general_issues/files/7817794/functional_annotation_list.xlsx)

**Comment by amcooksey** [comment]
Completed:
Bactrocera cucurbitae
Bactrocera dorsalis
Bactrocera_oleae
Bemisia_tabaci
Bombus_impatiens
Bombus_terrestris
[functional_annotation_list.xlsx](https://github.com/NAL-i5K/general_issues/files/7891852/functional_annotation_list.xlsx)

**Comment by amcooksey** [comment]
Completed:
Cephus_cinctus
Chelonus_insularis
Contarinia_nasturtii
[functional_annotation_list.xlsx](https://github.com/NAL-i5K/general_issues/files/7936258/functional_annotation_list.xlsx)

**Comment by amcooksey** [comment]
Completed:
Diachasma_alloeum
Diaphorina_citri
Drosophila_biarmipes
Drosophila_bipectinata
Drosophila_ficusphila
Drosophila_rhopaloa
Drosophila_takahashii
Dufourea_novaeangliae
[functional_annotation_list-3.xlsx](https://github.com/NAL-i5K/general_issues/files/8173198/functional_annotation_list-3.xlsx)

**Comment by amcooksey** [comment]
Completed:
Eufriesea_mexicana
Fopius_arisanus
Galleria_mellonella
Habropoda_laboriosa
Leptinotarsa_decemlineata
[functional_annotation_list-3.xlsx](https://github.com/NAL-i5K/general_issues/files/8234082/functional_annotation_list-3.xlsx)

**Comment by amcooksey** [comment]
Completed:
Nylanderia_fulva
Nicrophorus_vespilloides
Microplitis_demolitor
Megachile_rotundata
[functional_annotation_list-3.xlsx](https://github.com/NAL-i5K/general_issues/files/8544305/functional_annotation_list-3.xlsx)

**Comment by amcooksey** [comment]
Completed:
Odontomachus_brunneus
Osmia_lignaria
Varroa_jacobsoni
[functional_annotation_list-3.xlsx](https://github.com/NAL-i5K/general_issues/files/8604739/functional_annotation_list-3.xlsx)

**Comment by amcooksey** [comment]
This is the first batch of non-refseq I have done. I based the file and folder names on the names used in the file paths above.
Completed:
Tigriopus_californicus
Trichogramma_pretiosum
Pachypsylla_venusta
Parasteatoda_tepidariorum
[functional_annotation_list-3.xlsx](https://github.com/NAL-i5K/general_issues/files/8641957/functional_annotation_list-3.xlsx)

**Comment by amcooksey** [comment]
Completed:
Onthophagus_taurus
Orussus_abietinus
Melipona_quadrifasciata
Medauroidea_extradentata
Mayetiola_destructor
Manduca_sext
[functional_annotation_list-3.xlsx](https://github.com/NAL-i5K/general_issues/files/8836093/functional_annotation_list-3.xlsx)
a

**Comment by amcooksey** [comment]
Completed:
Locusta_migratoria
Lasioglossum_albipes
Laodelphax_striatellus
Ladona_fulva
Hyalella_azteca
Holacanthella_duospinosa
Heliothis_virescens
Halyomorpha_halys
Gerris_buenoi
Frankliniella_occidentalis
[functional_annotation_list-3.xlsx](https://github.com/NAL-i5K/general_issues/files/8864681/functional_annotation_list-3.xlsx)

**Comment by amcooksey** [comment]
Completed:
Anoplophora_glabripennis
Blattella_germanica
Catajapyx_aquilonaris
Centruroides_sculpturatus
Clitarchus_hookeri
Ephemera_danica
Euglossa_dilemma
[functional_annotation_list-3.xlsx](https://github.com/NAL-i5K/general_issues/files/8961498/functional_annotation_list-3.xlsx)
