### ISSUE TITLE
tripal 3 migration: convert custom drupal fields into chado properties

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#15]
## executive summary of solution
```
git clone https://gist.github.com/0dddfd015ff6ef1f545364c2ceff1f0b.git
drush scr 0dddfd015ff6ef1f545364c2ceff1f0b/Migrate_node_fields.php
rm -rf 0dddfd015ff6ef1f545364c2ceff1f0b
```

## description

Here are the fields on the site.
I think the ones we will want to convert are:  

* field_data_field_contig_n50
* field_data_field_gc_content
* field_data_field_image_credit (possibly?)
* field_data_field_community_contact
* field_data_field_number_of_genes
* field_data_field_scaffold_n50

I'm not sure right now if the correct way to do this is to load the organism, fetch the field (IE the drupal way), and insert the property, or to go through the field values via SQL instead.

I'm pretty sure that the entities are mapped where public.node's nid == the fields entity_id .

```
field_data_body
field_data_comment_body
field_data_field_community_contact
field_data_field_contig_n50
field_data_field_credit_line_and_copyright
field_data_field_file_image_alt_text
field_data_field_file_image_title_text
field_data_field_news_category
field_data_field_filename
field_data_field_image_credit
field_data_field_gc_content
field_data_field_hero_image
field_data_field_member_image
field_data_field_iframe
field_data_field_link_to
field_data_field_member_email_id
field_data_field_member_role
field_data_field_other_identifying_informat
field_data_field_number_of_genes
field_data_field_organism_image
field_data_field_photographer
field_data_taxonomy_vocabulary_5
field_data_field_resource_blocks
field_data_taxonomy_vocabulary_6
field_data_field_resource_links
field_revision_body
field_data_field_resource_titles
field_data_taxonomy_vocabulary_7
field_data_field_scaffold_n50
field_data_taxonomy_vocabulary_8
field_data_field_slider_image
field_data_taxonomyextra
```

**Comment by bradfordcondon** [comment]
Until I think more about how we want to do this, writing a gist for the conversion.  Its possible this would be a helpful utility for other groups so i want to leave room for that unless it seems like its going to add too much work...

In short, the key considerations are :

1- pick a cvterm beforehand for a given field.
2-  pick the target record.  Thats kind of tricky.  If its going on the same record (in oru case, organism) then its no problem.  If its going on a target record (perhaps in our case, analysis associated via analysis_organism linker table) then that has to happen beforehand.

https://gist.github.com/bradfordcondon/0dddfd015ff6ef1f545364c2ceff1f0b

**Comment by bradfordcondon** [comment]
proposed mapping terms:

* [contig n50](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001941)
* gc_content
* image_credit (possibly?)
* community_contact
* number_of_genes
* caffold_n50

**Comment by bradfordcondon** [comment]
ok.  the gist confirmed works for DIRECT MAPPING ie it creates organismsprops.

what i did was query the number of entries in the field, and confirm that the same number of organismprops were added to chado: they were.

Need to install the organism_analysis linker, assign a few organisms to analyses, and see if it properly creates analysisprops.

**Comment by mpoelchau** [comment]
Current plan: Migrate all drupal fields, deprecate some later via the Tripal eutils module. For example, Contig N50 should not be attached to organism - it should be an analysis property (and will be handled as such if imported via tripal eutils). For expediency's sake, we'll use Bradford's gist script to migrate, then update via Tripal eutils piecemeal.

**Comment by bradfordcondon** [comment]
Some fields shouldnt be chado properties!  This includes for example the image attribution field.

**Comment by mpoelchau** [comment]
Resource links: this is in issue #29.

**Comment by mpoelchau** [comment]
Community contacts: just migrate per Bradford's instructions now, but in future add to Chado contacts? Might want to use a bulk loader in future.

**Comment by bradfordcondon** [comment]
note: the convert is set up to insert it with the LINKED RECORD.

The gist MUST BE UPDATED by @bradfordcondon prior to run.  we dont want to insert the properties into the linked analysis.  we want to insert htem on the organism for now to keep things simple.

**Comment by bradfordcondon** [comment]
The following organism fields will be converted to organism props.
The ignored fields are either handled by core or not used.

| field name                                  | destination  | term                     |
|---------------------------------------------|--------------|--------------------------|
| field_data_field_community_contact          | organismprop | local:community_contact  |
| field_data_field_contig_n50                 | organismprop | local:contig_n50         |
| field_data_field_image_credit               | organismprop | local:image_credit       |
| field_data_field_gc_content                 | organismprop | local:gc_content         |
| field_data_field_other_identifying_informat | organismprop | local:identify_info      |
| field_data_field_number_of_genes            | organismprop | local:n_genes            |
| field_data_field_photographer               | organismprop | local:field_photographer |
| field_data_field_scaffold_n50               | organismprop | local:scaffold_n50       |

**Comment by mpoelchau** [comment]
- cloned into sites/all/modules/custom
- got the following error. Wondering if it's again a problem of not having the full database up on the dev site. 
```
drush scr 0dddfd015ff6ef1f545364c2ceff1f0b/Migrate_node_fields.php
Converting field: field_contig_n50 .   Converting field: field_gc_content .   Converting field: field_community_contact .   Converting field: field_number_of_genes .   Converting field: field_scaffold_n50 .   Converting field: field_photographer .   PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "field_data_field_photographer" does not exist                                                                      [error]
LINE 3: field_data_field_photographer ft
        ^ in /app/tripal3/drupal7/includes/database/database.inc:2227
Stack trace:
#0 /app/tripal3/drupal7/includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /app/tripal3/drupal7/includes/database/pgsql/database.inc(111): DatabaseStatementBase->execute(Array, Array)
#2 /app/tripal3/drupal7/includes/database/select.inc(1280): DatabaseConnection_pgsql->query('SELECT ft.field...', Array, Array)
#3 /app/tripal3/drupal7/sites/all/modules/custom/0dddfd015ff6ef1f545364c2ceff1f0b/Migrate_node_fields.php(115): SelectQuery->execute()
#4 /app/tripal3/drupal7/sites/all/modules/custom/0dddfd015ff6ef1f545364c2ceff1f0b/Migrate_node_fields.php(94):
ConvertFieldsToChadoProps->convert_all_instances_for_field('field_photograp...', '43564', 'organism', NULL, NULL)
#5 /app/tripal3/drupal7/sites/all/modules/custom/0dddfd015ff6ef1f545364c2ceff1f0b/Migrate_node_fields.php(20): ConvertFieldsToChadoProps->convert_all()
#6 phar:///app/local/bin/drush/commands/core/core.drush.inc(1162): include('/app/tripal3/dr...')
#7 phar:///app/local/bin/drush/includes/command.inc(422): drush_core_php_script('0dddfd015ff6ef1...')
#8 phar:///app/local/bin/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#9 phar:///app/local/bin/drush/includes/command.inc(199): drush_command('0dddfd015ff6ef1...')
#10 phar:///app/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#11 phar:///app/local/bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#12 phar:///app/local/bin/drush/includes/startup.inc(458): drush_main()
#13 phar:///app/local/bin/drush/includes/startup.inc(365): drush_run_main(false, '/', 'Phar detected. ...')
#14 phar:///app/local/bin/drush/drush(114): drush_startup(Array)
#15 /app/local/bin/drush(10): require('phar:///app/loc...')
#16 {main}
```

**Comment by bradfordcondon** [comment]
OK thats a field that existed on my copy of the db that didnt exist on your copy. 

We can remove the `field_data_field_photographer` field, or rewrite the gist to make sure the table exists before doing something with it.  That said I like crashing because if you are missing fields that i had, whos to say you dont also have fields that i didnt have and you want to migrate?

**Comment by mpoelchau** [comment]
There shouldn't be any additional fields. Fingers crossed.

I'd prefer either 1) rewrite the gist to make sure the table exists before doing something with or 2) having me figure out the database dump issues.

**Comment by bradfordcondon** [comment]
OK.  i just updated the gist to toss a warning and continue if the field doesn't exist.

**Comment by mpoelchau** [comment]
I get the following with the new script:

```
Warning: field_contig_n50  not present on this website.  Skipping.
Warning: field_gc_content  not present on this website.  Skipping.
Warning: field_community_contact  not present on this website.  Skipping.
Warning: field_number_of_genes  not present on this website.  Skipping.
Warning: field_scaffold_n50  not present on this website.  Skipping.
Converting field: field_photographer .
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "field_data_field_photographer" does not exist                                                                      [error]
LINE 3: field_data_field_photographer ft
        ^ in /app/tripal3/drupal7/includes/database/database.inc:2227
Stack trace:
#0 /app/tripal3/drupal7/includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /app/tripal3/drupal7/includes/database/pgsql/database.inc(111): DatabaseStatementBase->execute(Array, Array)
#2 /app/tripal3/drupal7/includes/database/select.inc(1280): DatabaseConnection_pgsql->query('SELECT ft.field...', Array, Array)
#3 /app/tripal3/drupal7/sites/all/modules/custom/0dddfd015ff6ef1f545364c2ceff1f0b/Migrate_node_fields.php(121): SelectQuery->execute()
#4 /app/tripal3/drupal7/sites/all/modules/custom/0dddfd015ff6ef1f545364c2ceff1f0b/Migrate_node_fields.php(100):
ConvertFieldsToChadoProps->convert_all_instances_for_field('field_photograp...', '43564', 'organism', NULL, NULL)
#5 /app/tripal3/drupal7/sites/all/modules/custom/0dddfd015ff6ef1f545364c2ceff1f0b/Migrate_node_fields.php(20): ConvertFieldsToChadoProps->convert_all()
#6 phar:///app/local/bin/drush/commands/core/core.drush.inc(1162): include('/app/tripal3/dr...')
#7 phar:///app/local/bin/drush/includes/command.inc(422): drush_core_php_script('0dddfd015ff6ef1...')
#8 phar:///app/local/bin/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#9 phar:///app/local/bin/drush/includes/command.inc(199): drush_command('0dddfd015ff6ef1...')
#10 phar:///app/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#11 phar:///app/local/bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#12 phar:///app/local/bin/drush/includes/startup.inc(458): drush_main()
#13 phar:///app/local/bin/drush/includes/startup.inc(365): drush_run_main(false, '/', 'Phar detected. ...')
#14 phar:///app/local/bin/drush/drush(114): drush_startup(Array)
#15 /app/local/bin/drush(10): require('phar:///app/loc...')
#16 {main}
```

**Comment by bradfordcondon** [comment]
sorry, my fault for rushing this before lunch.  `      if (db_table_exists($field_table)){` instead of `      if (!db_table_exists($field_table)){` . I updated the gist, please try again.

**Comment by mpoelchau** [comment]
Looks like this works and is integrated, closing.
