### ISSUE TITLE
Post Migration Organism editing

### ISSUE THREAD

**Issue by Ferrisx4** [NAL-i5K/general_issues#155]
When attempting to edit an organism page following a complete migration from Tripal 2 to Tripal 3, the following errors are thrown and the organism is not updated:

```PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" LINE 1: ..., '227535', 'bio_data_1', '0', 'und', '246', '', '', '', '') ^: INSERT INTO field_data_data__image (entity_type, entity_id, revision_id, bundle, delta, language, data__image_fid, data__image_alt, data__image_title, data__image_width, data__image_height) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10); Array ( ) in field_sql_storage_field_storage_write() (line 514 of /var/www/i5k/modules/field/modules/field_sql_storage/field_sql_storage.module).```

and

```Warning: Invalid argument supplied for foreach() in file_entity_set_title_alt_properties_on_file_fields() (line 248 of /var/www/i5k/sites/all/modules/contrib/file_entity/file_entity.file.inc).```

The dpm of the $record attempting to be written:
![dpm $record](https://user-images.githubusercontent.com/9593623/101207520-bb1c5300-363e-11eb-9582-b2f03a898b35.png)

**Comment by Ferrisx4** [comment]
While investigating this issue, Monica found [this old issue](https://github.com/NAL-i5K/general_issues/issues/33) which points us to the image being the source of the problem. Specifically, the problem arises when the image cannot be found on the webserver. If the image is not on disk, deleting the image from the Organism record via the Edit tab will resolve this issue (and allow the upload of a new image).

Upon further investigation into why this was happening, trying to recreate it was unsuccessful.

**Comment by mpoelchau** [comment]
I'll close this for now, as we've gone through our Tripal3 migration and this hasn't been a problem (so far).
