### ISSUE TITLE
Genome assembly update: Ladona fulva

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#162]
# Manual annotations

- [x] Manual annotation QC
- [x] OGS generation

# OGS remapping

- [x] request whole-genome alignment
- [x] run remap-gff3 on OGS

# Data management

- [x] submit OGS to NCBI
- [x] submit OGS to ADC
- [x] submit manual annotations on old assembly version to ADC

# Content deletion and addition steps

- [x] Run final-workflow.cwl on docker container - **use the localdata branch** (no RefSeq assembly available). 
  - Data locations: see below
  - Docker needed 14Gb allocation for bigwig step
- [x] Apollo2-stage: delete existing Apollo2 Ladona fulva organism (using UI, or web services, or apollo python library). Apollo2 stage URL: https://apollo2-stage-node1.nal.usda.gov/apollo/jbrowse
- [x] Pull processed data to Apollo2-stage
- [x] run movedata.cwl workflow as self user
- [x] Apollo2-stage: Add new Apollo2 data using createOrganism.py or createOrganism.cwl (parses YAML file)
- [x] Genomics-workspace-stage: use CLI to add new data. Change jbrowse settings to new assembly. Keep old blast files for now.
- [x] Test, if all works push to production
- [x] Tripal: add new genome assembly and annotations analysis pages, link to Organism page. Don't delete old assembly and annotation pages
- [x] deprecate old Apollo1 war and change link in 'available genome browsers' page (@mpoelchau)
- [x] data downloads setup (use create-symlink.cwl)
- [x] Final Test List
- [x] Advertising

# Data location:
- genome assembly: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/376/725/GCA_000376725.2_Lful_2.0/GCA_000376725.2_Lful_2.0_genomic.fna.gz
- genome annotations: https://data.nal.usda.gov/dataset/ladona-fulva-official-gene-set-ladfulogsv10

**Comment by mpoelchau** [comment]
@suryasaha the localdata branch of the Organism_onboarding repo now works for files that aren't retrieved from a URL. I need to add documentation, but you can use the file `final_workflow_short.yml` as a template. It adds the full path for the genome, gff, and other fasta files.

**Comment by mpoelchau** [comment]
@suryasaha can you remind me where this is at?

**Comment by suryasaha** [comment]
Add fasta
```
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addblast Ladona fulva -t nucleotide Genome Assembly -f /usr/local/i5k/media/blast/db/GCA_000376725.2_Lful_2.0_genomic.fna -d 'Ladona fulva genome assembly, Lful_2.0'
you can move to makeblastdb and populate sequence step
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addblast Ladona fulva -t nucleotide Transcript -f /usr/local/i5k/media/blast/db/ladful_OGSv1.0_trans.fa -d 'Ladona fulva Official Gene Set ladful OGSv1.0, transcripts'
you can move to makeblastdb and populate sequence step
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addblast Ladona fulva -t peptide Protein -f /usr/local/i5k/media/blast/db/ladful_OGSv1.0_pep.fa -d 'Ladona fulva Official Gene Set ladful OGSv1.0, translated CDS'
you can move to makeblastdb and populate sequence step
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addblast Ladona fulva -t peptide Protein -f /usr/local/i5k/media/blast/db/ladful_OGSv1.0_cds.fa -d 'Ladona fulva Official Gene Set ladful OGSv1.0, CDS'
you can move to makeblastdb and populate sequence step
```

Make blast DBs and populate
```
python manage.py blast_utility /usr/local/i5k/media/blast/db/GCA_000376725.2_Lful_2.0_genomic.fna -m
python manage.py blast_utility /usr/local/i5k/media/blast/db/GCA_000376725.2_Lful_2.0_genomic.fna -p


python manage.py blast_utility /usr/local/i5k/media/blast/db/ladful_OGSv1.0_trans.fa -m
python manage.py blast_utility /usr/local/i5k/media/blast/db/ladful_OGSv1.0_trans.fa -p

python manage.py blast_utility /usr/local/i5k/media/blast/db/ladful_OGSv1.0_pep.fa -m
python manage.py blast_utility /usr/local/i5k/media/blast/db/ladful_OGSv1.0_pep.fa -p

python manage.py blast_utility /usr/local/i5k/media/blast/db/ladful_OGSv1.0_cds.fa -m
python manage.py blast_utility /usr/local/i5k/media/blast/db/ladful_OGSv1.0_cds.fa -p
```

Make visible
```
python manage.py blast_shown /usr/local/i5k/media/blast/db/GCA_000376725.2_Lful_2.0_genomic.fna --shown true

python manage.py blast_shown /usr/local/i5k/media/blast/db/ladful_OGSv1.0_trans.fa --shown true

python manage.py blast_shown /usr/local/i5k/media/blast/db/ladful_OGSv1.0_pep.fa --shown true

python manage.py blast_shown /usr/local/i5k/media/blast/db/ladful_OGSv1.0_cds.fa --shown true
```




Add genome assembly fasta file to jbrowse
```
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addjbrowse /usr/local/i5k/media/blast/db/GCA_000376725.2_Lful_2.0_genomic.fna https://apollo.nal.usda.gov/apollo/Ladona%20fulva/jbrowse/
JBrowseSetting Successfully Created.
```

Set up hmmer for peptide fasta fila:
```
(i5k) [i5k@i5k-stage-node1 ~]$ python manage.py addhmmer Ladona fulva -f /usr/local/i5k/media/blast/db/ladful_OGSv1.0_pep.fa -d "Ladona fulva Official Gene Set ladful OGSv1.0, translated CDS"
Success
```

**Comment by suryasaha** [comment]
BLAST Protein - Ladona fulva Official Gene Set ladful OGSv1.0, CDS shoud be Nucleotide - Ladona fulva Official Gene Set ladful OGSv1.0, CDS

**Comment by suryasaha** [comment]
https://apollo.nal.usda.gov/apollo/jbrowse still has old genome

**Comment by suryasaha** [comment]
Does this need a new annotation page? Already have https://data.nal.usda.gov/dataset/ladona-fulva-official-gene-set-ladfulogsv10

**Comment by mpoelchau** [comment]
Yes, it needs a new annotation page. I'll set it up.

**Comment by mpoelchau** [comment]
Annotation page done: https://i5k.nal.usda.gov/bio_data/954998

**Comment by mpoelchau** [comment]
@suryasaha I just removed Ladona from prod apollo - the new one is good to load.

**Comment by suryasaha** [comment]
New genome looks good https://apollo.nal.usda.gov/apollo/4457810/jbrowse/index.html?loc=APVN02018775.1%3A185632..278438&tracks=DNA%2CAnnotations%2CGC%20Content%2CGaps%20in%20assembly%2Cladful_current_models&highlight=

**Comment by suryasaha** [comment]
Everything should be ok except this GS error on both stage and prod https://github.com/NAL-i5K/general_issues/issues/162#issuecomment-931434842

**Comment by mpoelchau** [comment]
Fixed the CDS error for blast.

**Comment by mpoelchau** [comment]
@mpoelchau needs to:
- add RNA-Seq
- add NCBI protein identifiers to off
- add gene pages

**Comment by mpoelchau** [comment]
@suryasaha can you make the ladful directory on apollo2-stage group-writable?

**Comment by suryasaha** [comment]
Thanks! The YML is in /app/data/surya.saha/Organism_Onboarding/jobs/ladful/ on apollo-stage
