### ISSUE TITLE
hyperlinks/hrefs in track description are not working in latest jbrowse on prod 

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#177]
With the latest updates to Jbrowse and Apollo on prod, hrefs in the 'About this track' pop-ups for the RNA-Seq tracks aren't working anymore: 

<img width="833" alt="Screen Shot 2021-10-01 at 9 57 48 AM" src="https://user-images.githubusercontent.com/5487172/135651364-6f30ba41-c37b-4435-bcc1-3b39b94ae6bb.png">

To see an example, go to the Venturia canescens jbrowse, select an RNA-Seq track, and click on 'About this track'

**Comment by mpoelchau** [comment]
Bumping this up again @childers

**Comment by childers** [comment]
I've done some minor testing to confirm this behavior, and tried formatting the links a few different ways.  

I then opened this issue up on the main repository: https://github.com/GMOD/jbrowse/issues/1617

**Comment by mpoelchau** [comment]
The tracklists should all be updated, and I've pushed the code changes to the nal-rnaseq pipeline.
