### ISSUE TITLE
page of drupal site is missing

### ISSUE THREAD

**Issue by hsiaoyi0504** [NAL-i5K/general_issues#18]
Recent CI job (https://travis-ci.org/NAL-i5K/GFF3toolkit/jobs/462844944)
shows that following page is missing:
https://i5k.nal.usda.gov/apollo-replaced-models-field-explanations-and-examples

@childers @mpoelchau @bradfordcondon Does it moved to other place ?

**Comment by bradfordcondon** [comment]
* the page is defined nowhere in the codebase (as determined by searching the repo for `apollo-replaced-models-field-explanations-and-examples`).  it was probably created via the GUI and therefore exists only in the database.
* Looks like the 508 issue person was able to find it: https://github.com/isdapps/i5k-tripal/issues/110

**Comment by mpoelchau** [comment]
Ah, thanks for looking into that, @hsiaoyi0504! 

I unpublished the page on our live site, since we don't recommend using the replace tag anymore. Apparently we still reference the page in the GFF3toolkit documentation, though. I'll fix it.

Handy that it can find broken links!

**Comment by mpoelchau** [comment]
I believe I fixed this in https://github.com/NAL-i5K/GFF3toolkit/pull/83.
