### ISSUE TITLE
make sure all apollo1 apps have web apollo plugin

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#182]
@childers can you check whether all apollo1 apps have the web apollo plugin? I checked the agrilus planipennis interface, and it looks like the plugin is missing. I have not checked all the apollo1 apps. Thanks!

**Comment by mpoelchau** [comment]
@childers the Apollo1 apps are missing the web apollo plugin: agrpla, homvit, onttau, helvir, partep, bacole

**Comment by childers** [comment]
Rolling back to the original config files. 
- [x ]  agrpla
- [ ] homvit
- [ ] onttau
- [ ]  helvir
- [ ]  partep
- [ ]  bacole

**Comment by mpoelchau** [comment]
Thanks @childers !
