### ISSUE TITLE
Add mapped RNA-Seq backlog to browsers

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#195]
[Previously,](url) Shelly ran the RNA-Seq mapping pipeline on a backlog of species that doesn't have RNA-Seq on the browsers. We now need to move these to the NAL servers and load them. 

Rough task list: 
- create new branch (from addtrack-scinet branch) with updated code for server. Update https://github.com/NAL-i5K/NAL_RNA_seq_annotation_pipeline/blob/addtrack_scinet/add_trackList/add_trackList.py
  - uncomment the symlink generation part
  - change singularity exec commands to docker run commands
- Pull jbrowse docker to apollo2-stage (can be your working directory). https://hub.docker.com/r/gmod/jbrowse
- pull RNA-Seq from scinet to apollo2-stage (can be your working directory). See attached list of containing directories. You'll need to scp or rsync the bam, bam.bai, bigwig, bed, and source files. [rna-seq directories.xlsx](https://github.com/NAL-i5K/general_issues/files/9011181/rna-seq.directories.xlsx)
- Run addtrack.py on list of species.
  - One of the arguments is the path to the tracklist.json file to modify. You can get this path from here: https://github.com/NAL-i5K/jbrowse_track_configs/blob/main/organisms_orig/directory_list.orig. You'll need to match up the RNA-Seq directory list on ceres with the NAL server path based on the six-letter abbreviation for the species. 
- Check stage browsers - does the RNA-Seq display? https://apollo2-stage-node1.nal.usda.gov/apollo/jbrowse
- Back up tracklists on apollo2-node1
- Push directories, symlinks, and tracklists to apollo2-node1
- check prod browsers. https://apollo.nal.usda.gov/apollo/jbrowse
- update permissions (apollo group, group writeable)

**Comment by mpoelchau** [comment]
@mpoelchau will need to help update the symlink portion of the code

**Comment by mpoelchau** [comment]
Oops, looks like we already had RNA-Seq for Chelonus insularis. I'll remove it, no need to propagate it to prod @amcooksey

**Comment by amcooksey** [comment]
removed maydes, hablab and copflo tracks from apollo-stage as they were mapped to the wrong assembly.
still need to sync data to apollo-prod.

**Comment by mpoelchau** [comment]
Sounds good. I have the scripts ready but haven't heard yet whether our permissions were fixed. We'll touch base again on Tuesday.

**Comment by mpoelchau** [comment]
Finished, created news item, closing - will advertise on mailing list in conjunction with functional annotations.
