### ISSUE TITLE
Move functional annotations from Ceres to NAL servers

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#196]
Now that @amcooksey has finished the functional backlog on Ceres, we need to move them to the NAL servers and make them accessible to our users.

I've attached 2 rough perl scripts to get this going, as well as a spreadsheet (i'll send via email) that we can use for moving things around.
- Pull data to i5k-stage server
- Move data into the appropriate directories (rough, unfinished stab at this in  https://gitlab.com/i5k_Workspace/monicas-data-processing-scripts/-/blob/master/move-func-annots.pl)
- make symlinks to the data downloads directories  (rough, unfinished stab at this in https://gitlab.com/i5k_Workspace/monicas-data-processing-scripts/-/blob/master/make-func-annot-datadir-symlinks.pl)
- test and move to prod (tbd how best to do this)
- Make Tripal functional annotation pages
- to be decided - ag data commons records?

**Comment by mpoelchau** [comment]
@amcooksey forgot to mention, let's leave out neolec for now. I'm coordinating with the community contact on the assembly update.

**Comment by amcooksey** [comment]
symlinks have been made. 
need to sync updates to i5k-prod.

**Comment by amcooksey** [comment]
added functional annotation Tripal pages for all organisms

**Comment by mpoelchau** [comment]
All functional annotations have been moved, and are accessible via Tripal pages and data downloads. I'll advertise once the Tripal link length bug is fixed on prod.
