### ISSUE TITLE
creation of a file upload field

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#2]
the primary purpose of this field would be to provide the datasets functionality of a secure file upload platform wiht some virus scanning I believe.  This was file_resup and something else.

I've already gotten pMC approval from 2/3 (stephen needs to sign off) for something very similar:  https://github.com/tripal/tripal/issues/642  in tripal core.

I think I can start working on a field that fills both roles in the context of providing it with tripal 3 core.

this issue is an adoption blocker of i5k from switching ti tripal_hq from the datasets module.

**Comment by bradfordcondon** [comment]
I started out by trying the core drupal files module.  This provides a files field that can be attached to content (much like i gave the example of attaching an "instutition" field users could fill out when creating a contact.

<img width="865" alt="screen shot 2018-10-19 at 4 48 34 pm" src="https://user-images.githubusercontent.com/7063154/47243251-6d412400-d3bf-11e8-9f62-def24e516147.png">
![Uploading Screen Shot 2018-10-19 at 4.50.27 PM.png…]()

it has all features out of the box we talked about minus security: ill look into that next.

**Comment by bradfordcondon** [comment]
The two missing bits of functionality that i can see from just the base file field with whatever additional modules enabled (file resup for example) are:

* Storing the file path in Chado (is this necessary/desired even?)
* Custom organization (again, would this be necessary/desired?)

**Comment by bradfordcondon** [comment]
security: https://www.drupal.org/project/clamav

**Comment by bradfordcondon** [comment]
I wrote a guide on how to do this for tripal, and how to export said file field.  When I configure your individual bundles i will export them as individual modules, one per bundle (one for organism, one for analysis, etc).  So, I'm marking this as done (but keeping open until i actually distribute the field, since we need to make sure the clamav and resup are working for it).

**Comment by mpoelchau** [comment]
Also see this tutorial: https://www.bradfordcondon.com/2018-11-09-understanding_drupal_features/
