### ISSUE TITLE
request: Zenodo access for the NAL-i5k organization

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#21]
I dont have permissions within the NAL-i5k organization but I'd like to add Zenodo integration for my public Tripal modules within the organization.

Zenodo creates DOIs which we can associate with software release and display on the repo.  See for example this release for rc1 of tripal_HQ

https://zenodo.org/record/1477063#.XBpcSs9KjUI

In order for this to work, we need to give Zenodo access to the organization the repo is in, ie NAL-i5K.  it will then detect when enabled modules create releases and create DOIs for them.

guide for adding access
https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/

**Comment by childers** [comment]
I can not find an interface that lets me add an application.  The interface I see is not what's in the linked doc. I'll keep looking

**Comment by childers** [comment]
This should be good. Closing for now.
