### ISSUE TITLE
More RNA-Seq updates

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#211]
We have a few more stragglers to generate RNA-Seq for. We'll need to do the mapping per the usual documentation, and add the data to the browsers on the servers. 

| Species name | Assembly to use |
| -------------- | ---------------- |
| Diachasma alloeum |  GCF_001412515.1 |
| Laodelphax striatellus | GCA_003335185.2 |
| Latrodectus hesperus | GCA_000697925.1 |
| Loxosceles_reclusa | GCA_001188405.1 |
| Habropoda_laboriosa | GCA_001263275.1 |
| Mayetiola_destructor | https://i5k.nal.usda.gov/data/Arthropoda/maydes-%28Mayetiola_destructor%29/Current%20Genome%20Assembly/1.Genome%20Assembly/Mayetiola_destructor_v1.0/Scaffolds/hf_scaffolds_agripestbase_ids.fa.gz |

**Comment by amcooksey** [comment]
Hablab: hard to find an example in the browser. this works: KQ414666.1:8630117..8631556 (1.44 Kb)

**Comment by mpoelchau** [comment]
Thanks @amcooksey !
