### ISSUE TITLE
Update functional annotation source URIs

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#213]
Our use of the 'source URI' field in the Tripal functional annotation pages has changed over time. We need to update the URIs to point to the i5k data downloads functional annotation directory (e.g. https://i5k.nal.usda.gov/data/Arthropoda/connas-(Contarinia_nasturtii)/AAFC_CNas_1.1/2.Official%20or%20Primary%20Gene%20Set/NCBI%20Contarinia%20nasturtii%20Annotation%20Release%20100%20functional%20annotation/)

I've attached a spreadsheet with the current URIs for all functional annotations on prod. The page URL can be built from the entity ID (e.g. if the entity ID is 1394304, then the page URL is https://i5k.nal.usda.gov/bio_data/1394304). You can look through the sheet to see which source URIs aren't pointing to the functional annotation directory, and update them. 

[funcannots.csv](https://github.com/NAL-i5K/general_issues/files/10060446/funcannots.csv)

**Comment by amcooksey** [comment]
@mpoelchau I think I've got the links fixed (except for two that I can't find any functional annotation through the data downloads page: apimel, athros). I will check the symlinks for these tomorrow.
I will also add the protein file to the functional annotation directories where necessary.

**Comment by amcooksey** [comment]
All of the source links were updated to the fucntional annotation directories. I pulled the protein file that was used into the functional annotation directory unless the file was already in the analysis directory. 

The one exception is apimel--I could not find the functional annotation.

**Comment by amcooksey** [comment]
Updated functional annotation source URL on Tripal to the functional annotation directory.
