### ISSUE TITLE
Update genome assembly source fields

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#217]
In the near future some of our metadata will be pulled by the EBP project. To that end our genome assembly metadata needs to be more consistent. Specifically, we need to update the source data to all point to the corresponding biosample record (older assembly records don't do this). While we're at it, we also need to add cross-references to Ag Data Commons. 

The task is to update the following fields based on the attached spreadsheet:
- Source name
- Source URL
- Cross reference accession (where available)
- make sure that the appropriate organism is selected - in many of these older assemblies it's not the case 

[not-biosamples.csv](https://github.com/NAL-i5K/general_issues/files/10551601/not-biosamples.csv)

**Comment by amcooksey** [comment]
All the fields are updated EXCEPT:
Lucilia cuprina doesn't have an organism page to reference

**Comment by mpoelchau** [comment]
Thanks @amcooksey ! Turns out the Lucilia cuprina pages shouldn't be published. I've unpublished them.
