### ISSUE TITLE
schistocerca download links

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#228]
@amcooksey some of the Schistocerca organism pages don't have a 'Download data' link to their data downloads folder (probably my fault) - could you go through these and add the links? I'm doing a training session on Thursday 3/30 so it would be nice to have those up before then.

Thanks!

**Comment by amcooksey** [comment]
@mpoelchau They should all have data downloads links now. I noticed that the some of the 'current genome assembly' links in the data downloads have backslashes. I was able to fix schser but schcan belongs to @childers  and schpic is yours.

**Comment by mpoelchau** [comment]
Thanks, I fixed schpic. @childers can you fix schcan? 

Also looks like we need to fix how set up the data directories (perhaps as the i5k user?)

**Comment by mpoelchau** [comment]
thanks for looking through this @amcooksey ! Does the documentation include logging in as the apollo user before running the script? I was able to ssh to i5k@i5k-stage-node1-cbo.nal.usda.gov from apollo2-stage after logging in as the apollo user.

**Comment by amcooksey** [comment]
@mpoelchau It was not in the documentation. I just confirmed that the transfer works using apollo. I added this step to the documentation for the movedata workflow.
