### ISSUE TITLE
Older organism pages need 'Download data' links

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#261]
Similar to #260, a bunch of older organism pages need links to the data downloads in the 'Links' section...

| link to org page | species|
| -----|-----|
| https://i5k.nal.usda.gov/bio_data/836554 | Anoplophora glabripennis |
| https://i5k.nal.usda.gov/bio_data/836497 | Centruroides sculpturatus |
| https://i5k.nal.usda.gov/bio_data/836495 | Cimex lectularius |
| https://i5k.nal.usda.gov/bio_data/836500 | Halyomorpha halys |
| https://i5k.nal.usda.gov/bio_data/836498 | Onthophagus taurus |
| https://i5k.nal.usda.gov/bio_data/836496 | Limnephilus lunatus |
| https://i5k.nal.usda.gov/bio_data/836534 | Leptinotarsa decemlineata |
| https://i5k.nal.usda.gov/bio_data/836511 | Parasteatoda tepidariorum |
| https://i5k.nal.usda.gov/bio_data/836555 | Agrilus planipennis |
| https://i5k.nal.usda.gov/bio_data/836560 | Eurytemora affinis complex (Atlantic clade) |
| https://i5k.nal.usda.gov/bio_data/836487 | Blattella germanica |
| https://i5k.nal.usda.gov/bio_data/836553 | Homalodisca vitripennis |
| https://i5k.nal.usda.gov/bio_data/836531 | Pachypsylla venusta |
| https://i5k.nal.usda.gov/bio_data/836535 | Hyalella azteca |
| https://i5k.nal.usda.gov/bio_data/836544 | Ephemera danica |
| https://i5k.nal.usda.gov/bio_data/836552 | Ceratitis capitata |
| https://i5k.nal.usda.gov/bio_data/836545 | Oncopeltus fasciatus |
| https://i5k.nal.usda.gov/bio_data/836528 | Trichogramma pretiosum |
| https://i5k.nal.usda.gov/bio_data/836530 | Orussus abietinus |
| https://i5k.nal.usda.gov/bio_data/836513 | Ladona fulva |
| https://i5k.nal.usda.gov/bio_data/836503 | Catajapyx aquilonaris |
| https://i5k.nal.usda.gov/bio_data/836493 | Athalia rosae |
| https://i5k.nal.usda.gov/bio_data/836518 | Gerris buenoi |
| https://i5k.nal.usda.gov/bio_data/836494 | Latrodectus hesperus |
| https://i5k.nal.usda.gov/bio_data/836537 | Frankliniella occidentalis |
| https://i5k.nal.usda.gov/bio_data/836551 | Diaphorina citri |
| https://i5k.nal.usda.gov/bio_data/836484 | Drosophila bipectinata |
| https://i5k.nal.usda.gov/bio_data/836502 | Drosophila elegans |
| https://i5k.nal.usda.gov/bio_data/836489 | Drosophila eugracilis |
| https://i5k.nal.usda.gov/bio_data/836485 | Drosophila ficusphila |
| https://i5k.nal.usda.gov/bio_data/836486 | Drosophila kikkawai |
| https://i5k.nal.usda.gov/bio_data/836491 | Drosophila rhopaloa |
| https://i5k.nal.usda.gov/bio_data/836492 | Drosophila takahashii |
| https://i5k.nal.usda.gov/bio_data/836483 | Loxosceles reclusa |
| https://i5k.nal.usda.gov/bio_data/836490 | Copidosoma floridanum |
| https://i5k.nal.usda.gov/bio_data/836504 | Tigriopus californicus |
| https://i5k.nal.usda.gov/bio_data/836488 | Mayetiola destructor |
| https://i5k.nal.usda.gov/bio_data/836561 | Manduca sexta |
| https://i5k.nal.usda.gov/bio_data/836540 | Bactrocera dorsalis |
| https://i5k.nal.usda.gov/bio_data/836501 | Fopius arisanus |
| https://i5k.nal.usda.gov/bio_data/836506 | Bactrocera oleae |
| https://i5k.nal.usda.gov/bio_data/836559 | Microplitis demolitor |
| https://i5k.nal.usda.gov/bio_data/836524 | Habropoda laboriosa |
| https://i5k.nal.usda.gov/bio_data/836510 | Lasioglossum albipes |
| https://i5k.nal.usda.gov/bio_data/836505 | Melipona quadrifasciata |
| https://i5k.nal.usda.gov/bio_data/836507 | Megachile rotundata |
| https://i5k.nal.usda.gov/bio_data/836508 | Dufourea novaeangliae |
| https://i5k.nal.usda.gov/bio_data/836542 | Tribolium castaneum |
| https://i5k.nal.usda.gov/bio_data/836549 | Amyelois transitella |
| https://i5k.nal.usda.gov/bio_data/836541 | Diachasma alloeum |
| https://i5k.nal.usda.gov/bio_data/836509 | Cephus cinctus |
| https://i5k.nal.usda.gov/bio_data/836514 | Eufriesea mexicana |
| https://i5k.nal.usda.gov/bio_data/836512 | Nicrophorus vespilloides |
| https://i5k.nal.usda.gov/bio_data/836548 | Aethina tumida |
| https://i5k.nal.usda.gov/bio_data/836515 | Locusta migratoria |
| https://i5k.nal.usda.gov/bio_data/836516 | Euglossa dilemma |
| https://i5k.nal.usda.gov/bio_data/836519 | Heliothis virescens |
| https://i5k.nal.usda.gov/bio_data/836529 | Apis mellifera |
| https://i5k.nal.usda.gov/bio_data/836556 | Bombus impatiens |
| https://i5k.nal.usda.gov/bio_data/836557 | Bombus terrestris |
| https://i5k.nal.usda.gov/bio_data/836517 | Bemisia tabaci |
| https://i5k.nal.usda.gov/bio_data/836543 | Clitarchus hookeri |
| https://i5k.nal.usda.gov/bio_data/836521 | Holacanthella duospinosa |
| https://i5k.nal.usda.gov/bio_data/836522 | Rhipicephalus microplus |
| https://i5k.nal.usda.gov/bio_data/836526 | Varroa destructor |
| https://i5k.nal.usda.gov/bio_data/836533 | Varroa jacobsoni |
| https://i5k.nal.usda.gov/bio_data/836527 | Mamestra configurata |
| https://i5k.nal.usda.gov/bio_data/836525 | Medauroidea extradentata |
| https://i5k.nal.usda.gov/bio_data/836532 | Laodelphax striatellus |
| https://i5k.nal.usda.gov/bio_data/836520 | Nylanderia fulva |
| https://i5k.nal.usda.gov/bio_data/836539 | Galleria mellonella |
| https://i5k.nal.usda.gov/bio_data/836538 | Contarinia nasturtii |
| https://i5k.nal.usda.gov/bio_data/836536 | Odontomachus brunneus |
| https://i5k.nal.usda.gov/bio_data/836546 | Osmia lignaria |
| https://i5k.nal.usda.gov/bio_data/836547 | Chelonus insularis |
| https://i5k.nal.usda.gov/bio_data/836558 | Photinus pyralis |
| https://i5k.nal.usda.gov/bio_data/836562 | Bradysia coprophila |
| https://i5k.nal.usda.gov/bio_data/836897 | Lucilia sericata |
| https://i5k.nal.usda.gov/bio_data/905593 | Venturia canescens |
| https://i5k.nal.usda.gov/bio_data/1212155 | Tribolium madens |

**Comment by mpoelchau** [comment]
@Ferrisx4 is there a way we could add new links to organisms (e.g. in the `public.field_data_bio_data_1_resource_links` table) programmatically? We can't currently update the organism table.

@amcooksey hold off on this until we figure out a mechanism...

**Comment by amcooksey** [comment]
Done!
