### ISSUE TITLE
Add analysisprop addition to genome assembly update workflow

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#263]
In order to programmatically check for genome updates, we need to add an analysisprop 'is_obsolete' to obsolete analyses. 

This is semi-documented in https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates#checking-for-genome-assembly-updates: Use the Tripal bulk loader 'Add is_obsolete to analysis' to add the is_obsolete analysisprop to the chado analysis (https://i5k.nal.usda.gov/admin/tripal/loaders/bulk/templates). Get the analysis id from... and add it to a text file. That text file needs to be uploaded to i5k:/app/i5k-tripal/wwwroot/sites/default/files/tmp. Then run bulk loader

I need to update the bulk loader so we can use a more useful key other than analysis_id. @amcooksey it would be great if you could 1) nag me to do the former, 2) update our documentation to make that more prominent, and then 3) test the workflow in https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates#checking-for-genome-assembly-updates.

**Comment by mpoelchau** [comment]
@amcooksey 
- I created a new bulk loader that you can test for this. https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/SOPs-for-I5k-Workspace-genome-project-updates#tripal-1
- You'll need to create a text file with the names of the genome assembly pages in them. E.g. `Whole genome assembly of Catajapyx aquilonaris` for https://i5k.nal.usda.gov/bio_data/836822
- Then follow the instructions on gitlab and let me know if they're confusing
- Also, I updated the genome assembly update issue template in this repo to include an item to add the is_obsolete prop to the old page

**Comment by amcooksey** [comment]
is_obsolete added to all obsolete genome assemblies on stage and prod EXCEPT  there are two "Hyalella azteca genome assembly Hazt_2.0 (GCF_000764305.1)" pages. The add analysis_prop by name doesn't work with this. It will have to be dealt with separately.

**Comment by amcooksey** [comment]
obsoleted the remaining old hyaazt assembly.

**Comment by amcooksey** [comment]
made minor updates to the documentation.
