### ISSUE TITLE
New organism: Laodelphax striatella

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#27]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/wikis/Adding-an-organism-to-the-i5k-Workspace-NAL-version for full description of each task.

Genome project URL: https://www.ncbi.nlm.nih.gov/assembly/GCA_003335185.2
Checksums:
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/335/185/GCA_003335185.2_ASM333518v2/md5checksums.txt
Genome assembly: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/335/185/GCA_003335185.2_ASM333518v2/GCA_003335185.2_ASM333518v2_genomic.fna.gz
Genome gff: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/335/185/GCA_003335185.2_ASM333518v2/GCA_003335185.2_ASM333518v2_genomic.gff.gz
Protein fasta: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/335/185/GCA_003335185.2_ASM333518v2/GCA_003335185.2_ASM333518v2_translated_cds.faa.gz
CDS fasta: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/335/185/GCA_003335185.2_ASM333518v2/GCA_003335185.2_ASM333518v2_cds_from_genomic.fna.gz
RNA fasta: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/335/185/GCA_003335185.2_ASM333518v2/GCA_003335185.2_ASM333518v2_rna_from_genomic.fna.gz

- [x] 1. Set up data directories and get data
- [x] 2. Verify data
- [x] 3. Data wrangling for Apollo setup
- [x] 4. Apollo2 setup
- [x] 5. Tripal setup
- [x] 6. BLAST setup
- [x] 7. HMMER setup
- [x] 8. data downloads setup
- [x] 9. Final Test List
- [x] 10. Advertising

**Comment by r06942072** [comment]
perl scripth on apollo-dev:
/app/data/WebApollo_deployment/Apollo2_master/jbrowse-download/bin

**Comment by r06942072** [comment]
```cwl-runner final-workflow.cwl job-laostr.yml```
[Step 1. Success]
![step1_success.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/91ff7f01-fa1d-4f3c-a975-01475ab735b9)

**Comment by r06942072** [comment]
migrate detail progress to gitlab #797.

**Comment by mpoelchau** [comment]
Organism (finally!) added.
