### ISSUE TITLE
problem with description fields

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#28]
Note, this info is now redundant with the migration guide repo, please use that instead.

### executive summary
(to be done prior to migration)

- disable `ckeditor` and `wysiwyg_filter` (should have been done prior to migration)
- create new filters that are copies of the full_Html and filtered_html filters at `admin/config/content/formats/`.  Rename the old filters "filter name (Don't use)".
- now when you migration analysis and organism nodes, the descriptions should display.

### description
Description fields dont migrate correctly from t2-t3. This is for organisms and analysis.  

https://github.com/tripal/tripal/issues/721

I think disabling the custom WYSIG editors is part of the solution.  However even then changing hte input type to "full HTML" or filtered HTML doesnt work, and the field doesnt display.  returning to the edit page means the text format box still isnt set;

<img width="659" alt="screen shot 2019-03-03 at 4 47 37 pm" src="https://user-images.githubusercontent.com/7063154/53702360-153a1580-3dd4-11e9-934b-4b3405d7dcea.png">

**Comment by bradfordcondon** [comment]
here's a summary of the problem and the workaround.

https://github.com/tripal/tripal/issues/868#issuecomment-469292799

**Comment by Ferrisx4** [comment]
While no automated way to accomplish this task has been found, the manual workaround above succeeds and is documented and included in the Upgrade Guide, https://github.com/NAL-i5K/T2-to-T3-Upgrade-Guide

**Comment by mpoelchau** [comment]
Thanks @Ferrisx4 , looks like we can close this.
