### ISSUE TITLE
Set up analysis field on organism page

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#31]
One of the next steps to customize the organism page is to create a field for analysis. Tried to do this using the tripal_manage_analyses module (https://github.com/statonlab/tripal_manage_analyses.git). Got WSOD, no useful log messages. @bradfordcondon will test. 

Otherwise, we are good for the analysis bundle/content type, because we didn't do any customizations.

**Comment by bradfordcondon** [comment]
WSOD is from php version < 7.1 . If WSOD occurs when enabling module, this is the most likely cause: disable the module and visit `/admin/reports/status` to check the php version.

Module to confiugre analysis bundle (linked organism field attached) is forthcoming.

**Comment by bradfordcondon** [comment]
this field should be automatically installed and configured when enabling the i5k analysis config module here: https://github.com/NAL-i5K/i5k_analysis

**Comment by bradfordcondon** [comment]
the analysis browser field was hopelessly broken... someone probably half-messed with it but didnt finish.
  Resolved here on master https://github.com/statonlab/tripal_manage_analyses/pull/73

![Screen Shot 2019-03-25 at 2 36 48 PM](https://user-images.githubusercontent.com/7063154/54945105-718fe100-4f0b-11e9-926c-54f59b8cc3cf.png)
