### ISSUE TITLE
Tripal 3 migration

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#34]
* make new database dump from stage
* disable custom module x before step 1 to prevent breaking site.
* [Follow step 1 of migration guide](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html#step-1-upgrade-tripal).  This replaces the v2 code with v3, and enacts the basic database changes.
* disable  extra text filter modules
* create new text filers /rename old text filters
* [Migrate Content](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html#step-2-migrate-content)
  -   Migrate Content: organism 
  -   Migrate Content: analysis
* Run custom migration scripts that deals with custom organism properties (#15 ) [Gist script ](https://gist.github.com/bradfordcondon/0dddfd015ff6ef1f545364c2ceff1f0b)
* enable tripal_manage_analyses module

* Run custom migration script that takes internal "links" and inserts them into organism_analysis linker table [gist code](https://gist.github.com/bradfordcondon/ec7078b8514a422e65db5e8d6cd29858)

* enable custom i5k field display modules written by BC (WIP)

* Perform step 4 of migration: [unpublish nodes and copy url aliases/titles](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html#step-4-delete-tripal-v2-content-and-publish-tripal-v3-content)

Waiting on BC

  -   Migrate Content: feature (gene fields need to get into tripal core)

**Comment by bradfordcondon** [comment]
I wrote up a full guide to make this easier:its here https://github.com/NAL-i5K/T2-to-T3-Upgrade-Guide

It's sitll a mix of automated and manual steps.  However, now at least the scripts etc are all in one place instead of in separate gists.

**Comment by mpoelchau** [comment]
This has been replaced by: https://github.com/Ferrisx4/T2-T3_Ferris-Saga. Closing.
