### ISSUE TITLE
organism taxid is required 

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#36]
In our Tripal3 organism setup, taxid is required. I'm guessing this is because we are using the chado organism input page as the place for new users to submit organism information, and we've been requiring the organism ID.

In editing one of our existing organisms (add an image), I got the warning that taxid was required. I entered it, and then got the following error:

![taxid_error](https://user-images.githubusercontent.com/5487172/54547140-c6ab8000-496a-11e9-9b8a-974b1fa99dd7.png)

@bradfordcondon do you know why I'm getting that error?

A separate issue is to revisit the whole taxid is required thing. For now it might be easier to drop this requirement. We will need to revisit the whole workflow of having users onboard data with Tripal HQ + Tripal eutils, anyway.

**Comment by bradfordcondon** [comment]
I have this error on my copy too.

Setting the field to optional does not resolve.

I thought maybe the fieldgroup I put them in is the problem, but couldnt recreate the problem with just that.  Some combination of the fieldset AND the property?

**Comment by bradfordcondon** [comment]
I deleting the tax_id property and the fieldgroup they were all in:

Now I just get this error

```
Could not save the TripalEntity: Could not insert Chado record into table: "organism": Array ( [abbreviation] => jlkjklj [species] => jlkjlkj [genus] => jkjlkj [comment] => jlkjlkj [common_name] => __NULL__ [type_id] => __NULL__ [infraspecific_name] => __NULL__ )

```

I can create other content type still.

New idea: its the analsyis linker field, as its not displaying correctly either...

**Comment by mpoelchau** [comment]
This seems to be resolved (not getting the same error on the midspin site). Closing.
