### ISSUE TITLE
upgrade chado 1.2 to 1.3

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#37]
@mpoelchau reported an error when enabling the `eutils` module- this is because it expects a Chado 1.3 table.  

I5k is on chado 1.2.

The Tripal automatic upgrade gives us this error:
```
alling: tripal_chado_install_chado(Upgrade Chado v1.2 to v1.3)
Checking for existing v1.3 tables in v1.2 and fixing bigints...
Incorporating additional changes...
Loading sites/all/modules/contrib/tripal/tripal_chado/chado_schema/default_schema-1.2-1.3-diff.sql...
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] FAILED. Line  1853, 0SQLSTATE[42809]: Wrong object type: 7 ERROR:  "all_feature_names" is not a viewHINT:  Use DROP TABLE to remove a table.:DROP VIEW IF EXISTS all_feature_names CASCADE;
```

Unfortunately, this is a pain.  Fortunately, I've been through it before and its [all documented in the issue here on our HWG site](https://github.com/statonlab/hardwoods_site/issues/268)

Also relevant: [issue in tripal core](https://github.com/tripal/tripal/issues/372)

**Comment by bradfordcondon** [comment]
Highlights:

The views need to be dropped first (as the above error suggests).

This script generates a script that will drop all the views

```
set search_path=public,so,frange,genetic_code;
select 'drop view "' || viewname || '" cascade;' 
from pg_views where schemaname = 'so';
```

**Comment by bradfordcondon** [comment]
after generating the drop script as instructed above - 

```
Calling: tripal_chado_install_chado(Upgrade Chado v1.2 to v1.3)
Checking for existing v1.3 tables in v1.2 and fixing bigints...
Incorporating additional changes...
Loading sites/all/modules/contrib/tripal/tripal_chado/chado_schema/default_schema-1.2-1.3-diff.sql...
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] FAILED. Line  1853, 0SQLSTATE[42809]: Wrong object type: 7 ERROR:  "all_feature_names" is not a viewHINT:  Use DROP TABLE to remove a table.:DROP VIEW IF EXISTS all_feature_names CASCADE;
```

**Comment by bradfordcondon** [comment]
I manually deleted the `all_feature_names` table.  Looking at the [Chado definition](https://github.com/GMOD/Chado/blob/0ddab3c8f8da9c7d7a5f627d5f37517380affd6b/chado/modules/sequence/sequence_views.sql) it really appears to be a view, not a table... so... I dunno.  I'm going to delete it and move on.  I created a [core issue](https://github.com/tripal/tripal/issues/896), maybe someone will inform me that i shouldnt drop it.


` DROP TABLE IF EXISTS all_feature_names CASCADE;`


This brings us to the next error-

```
Calling: tripal_chado_install_chado(Upgrade Chado v1.2 to v1.3)
Checking for existing v1.3 tables in v1.2 and fixing bigints...
Incorporating additional changes...
Loading sites/all/modules/contrib/tripal/tripal_chado/chado_schema/default_schema-1.2-1.3-diff.sql...
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] FAILED. Line  2374, 0SQLSTATE[0A000]: Feature not supported: 7 ERROR:  cannot alter type of a column used by a view or ruleDETAIL:  rule _RETURN on view so.genotype depends on column "feature_id":ALTER TABLE feature     ALTER feature_id TYPE  bigint,    ALTER dbxref_id TYPE bigint,    ALTER organism_id TYPE bigint,    ALTER seqlen TYPE bigint,    ALTER type_id TYPE bigint;
```

**Comment by bradfordcondon** [comment]
looks like to resolve the disk space issue, we [disabled transactions on HWG](https://github.com/statonlab/hardwoods_site/issues/268#issuecomment-393615253)

**Comment by mpoelchau** [comment]
@bradfordcondon can you write up a step-by-step guide for me based on your observations in this thread? I could re-capitulate all your steps, but it seems like there was a lot of trial and error here. I'd like to prioritize this (maybe even do this today).

**Comment by bradfordcondon** [comment]
OK sure!  I'm in the middle of setting up a single repository that will run all of the gists etc/unite all the upgrade issues.  I'll put that on hold and do that for you instead.

**Comment by mpoelchau** [comment]
thanks!

**Comment by bradfordcondon** [comment]
Tripal has a GUI to run the Chado 1.2 to 1.3 migration.  However, it doesn't run smoothly on many sites.  There are three main reasons for this:

* Your site has views Tripal didn't expect
* Your site has some views as tables instead
* The database transaction requires more disk space than your site has free


### dropping views

The first thing to do is create a drop script.  The below SQL will output an SQL script that will drop all the chado and so (sequence ontology) views from your site (something the migration script attempts to do at the start.)


```sql
set search_path=public,so,frange,genetic_code;
select 'drop view "' || viewname || '" cascade;'
from pg_views where schemaname = 'so';

select 'drop view "' || viewname || '" cascade;'
from pg_views where schemaname = 'chado';
```

We can use drush to generate the drop query like so: `drush sql-query  --file generate_drop_file.sql result-file drop_script.sql` where `generate_drop_file` is our input drop script above.


Once you've generated the drop script, you should run it.  All together it will look like this:

```bash

drush sql-query --file generate_drop_file.sql result-file drop_script.sql
drush sql-query --file drop_script.sql

```

## dropping tables that SHOULD be views

Oddly enough the `chado.all_feature_names` table is SUPPOSED to be a view according to the Chado documentation.  We therefore need to drop it, otherwise the script will complain when it tries to drop the view!

```SQL
set search_path=chado;
 DROP TABLE IF EXISTS all_feature_names CASCADE;
```

## Disabling the transaction

You are now ready to try running the migration!  It's located at`/admin/tripal/storage/chado/install`.  You should see 1.2 as the currently installed version- select "upgrade existing Chado v1.2 to v1.3 (no data is lost)".  You will see lots of warnings/notices informing you about what this ugpgrade will.  Notably, you should plan on **redefining any custom materialized views** after running the migration to hold big integers instead of integers.

If you run the migration and get the bellow error, you have run out of space!

```
Disk full: 7 ERROR:  could not extend file "base/40960/269560.3": No space left on deviceHINT:  Check free disk space.:ALTER TABLE feature     ALTER feature_id TYPE  bigint,    ALTER dbxref_id TYPE bigint,    ALTER organism_id TYPE bigint,    ALTER seqlen TYPE bigint,    ALTER type_id TYPE bigint;

```

You have two strategies to overcome this:

1) Increase your disk space
2) Disable the transaction in the code


If 1) doesnt work or isn't possible, just comment out the transaction in the `tripal_chado.install.inc` file (`tripal/tripal_chado/includes/tripal_chado.install.inc`), which is currently on lines 221/244.

Before
```php

$transaction = db_transaction();
try {
  if ($action == 'Install Chado v1.3') {
    tripal_chado_install_chado_1_3();
    chado_query($vsql, [':version' => '1.3']);
  }
  elseif ($action == 'Upgrade Chado v1.2 to v1.3') {
    tripal_chado_upgrade_chado_1_2_to_1_3();
    chado_query($vusql, [':version' => '1.3']);
  }
  elseif ($action == 'Install Chado v1.2') {
    tripal_chado_install_chado_1_2();
    chado_query($vsql, [':version' => '1.2']);
  }
  elseif ($action == 'Upgrade Chado v1.11 to v1.2') {
    tripal_chado_upgrade_chado_1_11_to_1_2();
    chado_query($vsql, [':version' => '1.2']);
  }
  elseif ($action == 'Install Chado v1.11') {
    tripal_chado_install_chado_1_11();
  }
} catch (Exception $e) {
  $transaction->rollback();
  tripal_chado_install_done();
  tripal_report_error('tripal_chado', TRIPAL_ERROR, $e->getMessage(), ['print' => TRUE]);
  return FALSE;
}

```

After

```php

//$transaction = db_transaction();
try {
  if ($action == 'Install Chado v1.3') {
    tripal_chado_install_chado_1_3();
    chado_query($vsql, [':version' => '1.3']);
  }
  elseif ($action == 'Upgrade Chado v1.2 to v1.3') {
    tripal_chado_upgrade_chado_1_2_to_1_3();
    chado_query($vusql, [':version' => '1.3']);
  }
  elseif ($action == 'Install Chado v1.2') {
    tripal_chado_install_chado_1_2();
    chado_query($vsql, [':version' => '1.2']);
  }
  elseif ($action == 'Upgrade Chado v1.11 to v1.2') {
    tripal_chado_upgrade_chado_1_11_to_1_2();
    chado_query($vsql, [':version' => '1.2']);
  }
  elseif ($action == 'Install Chado v1.11') {
    tripal_chado_install_chado_1_11();
  }
} catch (Exception $e) {
//  $transaction->rollback();
  tripal_chado_install_done();
  tripal_report_error('tripal_chado', TRIPAL_ERROR, $e->getMessage(), ['print' => TRUE]);
  return FALSE;
}
```

**Comment by mpoelchau** [comment]
Note to my future self - the 'executive summary' steps worked. Will need to keep this open for when we set up the final copy of the database.

**Comment by bradfordcondon** [comment]
Note: this is part of the ["T2-to-T3" migration repo](https://github.com/NAL-i5K/T2-to-T3-Upgrade-Guide/blob/master/Upgrading_chado_1.2_to_1.3.md).  It does require some manual steps.

**Comment by mpoelchau** [comment]
@Ferrisx4 can you confirm the chado 1.2 to 1.3 upgrade is part of the current migration process, and if so, close this issue?

**Comment by Ferrisx4** [comment]
Dropping the views is part of the pre-migration scripts: [generate_drop_file.sql](https://github.com/NAL-i5K/T2-to-T3-Upgrade-Guide/blob/master/scripts/generate_drop_file.sql).  

These scripts get called before initiating the Chado 1.2 to 1.3 upgrade.
