### ISSUE TITLE
gene pages don't retrieve child feature sequence

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#38]
The current gene page implementation doesn't retrieve the residues for child features (RNAs and proteins). It would be awesome if it could do that. Related to #32 and #5.

**Comment by bradfordcondon** [comment]
Best issue on core for this: https://github.com/tripal/tripal/issues/891

**Comment by bradfordcondon** [comment]
Here's the current implementation of this.

I think we liked the sequences being behind a popup, I'll do that instead.

The code for this is actually simple because im using `chado_get_feature_sequences()` to build the sequences.  However, we're going to want to make sure that this function is working correctly on i5k data, as there are lots of options one can pass to it to get it to build the sequences from related features.

![Screen Shot 2019-03-22 at 2 51 11 PM](https://user-images.githubusercontent.com/7063154/54846334-f41d6400-4cb1-11e9-9794-a4b0d2ab6cc3.png)

**Comment by bradfordcondon** [comment]
Here is my approach (PHP code below).

- Display sequence for mRNA, polypeptide, and CDS.
- polypeptide = should be in feature.residues
- CDS = derive it from children (exons)
- mRNA = derive it from parent (contig location).

This works as expected for CLEC008626.    Will this approach work for all features in i5k?  Do I need to support more sequence types? 

Honestly this probably means the module wants to provide some advanced configuration so you can specify what feature types to show sequence for, and how to derive it.  For now, it's hard coded like that. 


![Screen Shot 2019-03-25 at 2 03 08 PM](https://user-images.githubusercontent.com/7063154/54943007-bc5b2a00-4f06-11e9-9763-2beedbf944c6.png)



```php
    $check = ['polypeptide', 'mRNA', 'CDS'];

    if (!in_array($type, $check)) {
      $out = 'N/A';
      return $out;
    }

    $options = ['width' => 40, 'is_html' => 1];

    // TODO: add in more options based on the sequence we're looking at.
    // aggregate: Set to '1' if the sequence should only contain sub features, excluding intro sub feature sequence. For example, set this option to obtain just the coding sequence of an mRNA.
    // sub_feature_types: Only include sub features (or child features) of the types provided in the array.
    // TODO: I guess this should be done in the LOAD instead of the formatter?

    IF ($type == 'CDS') {

$options['aggregate'] = 1;
$options['sub_feature_types'] = ['exon'];

    }
    $returned = chado_get_feature_sequences(['feature_id' => $info->feature_id], $options);

if (!$returned[0]['residues']) {
  $options['derive_from_parent'] = 1;
  $returned = chado_get_feature_sequences(['feature_id' => $info->feature_id], $options);
}
```

**Comment by mpoelchau** [comment]
we are using the tripal core gene pages now, closing.
