### ISSUE TITLE
Add a new script for checking the file encoding of gff3 files

### ISSUE THREAD

**Issue by childers** [NAL-i5K/general_issues#4]
We have an issue related to file encoding.
We need to check a file is ascii only or utf-8.

Furthermore, if we can come up with a script that can inter-convert between these two formats.

See:
https://gitlab.com/i5k_Workspace/workspace_roadmap/issues/734

**Comment by mpoelchau** [comment]
@deming7h777 you can try this file: https://i5k.nal.usda.gov/data/Arthropoda/cimlec-(Cimex_lectularius)/Current%20Genome%20Assembly/2.Official%20or%20Primary%20Gene%20Set/OGS_v1_2/clec_OGS_v1_2.gff3.gz

Or if you need something smaller, you can use greek characters, e.g. https://cloford.com/resources/charcodes/utf-8_greek-extended.htm

**Comment by deming7h777** [comment]
![image](https://user-images.githubusercontent.com/33312760/47674841-a2ebc700-db8e-11e8-9ca6-29d83b57c93d.png)

i think it is work but i still need to make sure because it seems identical after converting

**Comment by hsiaoyi0504** [comment]
Hmm ... I would like to follow up this issue. It seems that this issue has been closed, but I didn't see any related change to gff3 toolkit. Or, do we decide not to do this ?

**Comment by mpoelchau** [comment]
Not a priority now, closing.
