### ISSUE TITLE
Travis for wiggle-tools

### ISSUE THREAD

**Issue by tony006469** [NAL-i5K/general_issues#40]

**Comment by tony006469** [comment]
Travis Ci for Wiggle-tools
![screenshot.png](https://images.zenhubusercontent.com/5bc4a57039f03821ed48e81f/0d9ec710-b679-43de-b9c0-17f3845c36d4)

**Comment by tony006469** [comment]
https://travis-ci.org/NAL-i5K/wiggle-tools/jobs/512214063
![screenshot-done.png](https://images.zenhubusercontent.com/5bc4a57039f03821ed48e81f/a606182e-3ea9-40b9-94dc-ea73c7d47e95)

**Comment by hsiaoyi0504** [comment]
@tony006469 It will be good to put a badge for Travis in README.md.

**Comment by hsiaoyi0504** [comment]
Included in NAL-i5K/wiggle-tools#6.
