### ISSUE TITLE
hardcoded nodes in analysis.sourceuri

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#41]
```
select count(*) from chado.analysis where sourceuri LIKE '%node%';
51
```

![Screen Shot 2019-03-27 at 10 48 51 AM](https://user-images.githubusercontent.com/7063154/55085959-ef73f980-507d-11e9-83db-991aa4f85d65.png)

What this means is that we need to write a custom migration script.  The source seems to always (?) be another analysis.

The "Chado" way to store this information would be to put it in `chado.analysis_relationship` instead.    Source URI is nullable and not part of the unique constraint, so you could null it.  If you want to keep the info in sourceuri, then you need to update the node linke to the entity link.

  However, if the sourceuri goes to a node that ISNT an analysis, then you're in trouble because that shouldnt go in `analysis_relationship`.

update:  they were all analyses on my copy.   There are some error messages that will alert you if the node didnt correspond to an analysis.

**Comment by bradfordcondon** [comment]
sourceuris follow one of the following patterns:

* `/node/739265/edit`
* `https://i5k.nal.usda.gov/node/739175/`
* `node/683157`
* `https://gmod-stage.nal.usda.gov/node/739377`
* `/node/739175`
* `/node/139958/`

Therefore, to fetch the nid

- drop everything leading up to and including `/node/` . 
- drop anything remaining after and including `/`


we'll verify the node is an analysis, insert the relationship, look up the entity id, and then  change  the sourceuri to be `/bio_data/[entity_id]`

**Comment by bradfordcondon** [comment]
Added to the upgrade guide.  It will run automatically in [the "post migrate" script](https://github.com/NAL-i5K/T2-to-T3-Upgrade-Guide#after-migrating).  Needs to be after as we need both nodes and entity ids.

Actual script can be viewed here:

https://github.com/NAL-i5K/T2-to-T3-Upgrade-Guide/blob/master/scripts/convert_sourceuris_from_nodes.php

**Comment by bradfordcondon** [comment]
After running script

![Screen Shot 2019-03-27 at 12 13 10 PM](https://user-images.githubusercontent.com/7063154/55092867-bb9ed100-5089-11e9-8117-1a55eb5f8c0b.png)

note we dont have relationship field enabled for analysis .    Enabling it gives us problems for some reason - 
![Uploading Screen Shot 2019-03-27 at 1.06.32 PM.png…]()

**Comment by bradfordcondon** [comment]
Created [issue Tripal core](https://github.com/tripal/tripal/issues/911) and created [PR to resolve](https://github.com/tripal/tripal/pull/912)

**Comment by mpoelchau** [comment]
Looks like this is resolved. Closing.
