### ISSUE TITLE
New organism: Varroa jacobsoni

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/general_issues#48]
See https://gitlab.com/i5k_Workspace/workspace_roadmap/wikis/Adding-an-organism-to-the-i5k-Workspace-NAL-version for full description of each task.

- [x] 1. Set up data directories and get data
- [x] 2. Verify data
- [x] 3. Data wrangling for Apollo setup
- [x] 4. Apollo2 setup
- [x] 5. Tripal setup
- [x] 6. gene pages
- [x] 7. BLAST setup
- [x] 8. HMMER setup
- [x] 9. data downloads setup
- [x] 10. Final Test List
- [x] 11. Advertising

**Comment by childers** [comment]
Prepping Apollo 2:
Server:
 ``` apollo-stage-node1 ```
Path: 
 ``` /app/data/other_species/varjac/vjacob_1.0/ ```

**Comment by mpoelchau** [comment]
FYI - detailed documentation of the issue is here: https://gitlab.com/i5k_Workspace/workspace_roadmap/issues/781

**Comment by childers** [comment]
@mpoelchau thanks! I had forgotten about that.
