### ISSUE TITLE
Moving the i5k gene page to tripal 3

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#5]
https://i5k.nal.usda.gov/CLEC010822
vs
http://167.99.232.220/gene/185

My plan:

* Demonstrate the "default" feature layout in tripal 3.  
* Identify what content would belong as new fields, custom modules, etc.

I'll get the demo site up so that i can link to compare screenshots and then fill out the rest of the below...

First impressions:
### General
The Overview, sequences, and Transcript "tabs" are set up as tripal panes in tripal 3.  It will take some custom styling to get them looking like you want (although the horizontal layout is a default option i think).

### Overview tab

![Screen Shot 2018-10-30 at 2.17.28 PM.png](https://images.zenhubusercontent.com/5ba274c1d9f3872b96041c42/a38120f9-b747-4ebd-868a-79c36a35fbcc)

Pre-exsting Chado fields:

* organism
* Name
* synonyms
* location
* transcripts
* analysis links

Depends on how its stored in the db:

* gene ID (featureprop?  uniquename?)
* annotator comments (featureprops?)

## Transcripts

So CLEC010822-RA doesnt have its own page?  I actually like this a lot.  Something I dont like about Tripal 3 genes is they only display select info about child features, and link out to child genes proteins etc.  I like it much better all displayed on the gene page.

* annotated terms:
 - is this feature_cvterm?  if so, pre-existing field
* feature details:

hmm start/stop of each subfeature, i dontk now that this exists.  Subfeatures get listed as relationships, and sequences get listed in their relevant fields.  I can imagine this becoming a custom field.

**Comment by bradfordcondon** [comment]
i was going to use my mini devseed, but i realize that isnt a great representation of your data since its mRNA focused instead of gene focused. 

I will therefore load the bee genome from https://i5k.nal.usda.gov/content/data-downloads

**Comment by bradfordcondon** [comment]
ok so lets compare this to a DEFAULT gene page.

Note- i dont have any sequences appearing.  This is a mistake on my end, i loaded scaffold, protein, and CDS fasta sequences and associated the sequences with the CDS.  The fields by default on gene want to display the mRNA-associated sequences :( 

http://167.99.232.220/gene/185


![screen shot 2018-10-31 at 9 49 49 am](https://user-images.githubusercontent.com/7063154/47792389-53261080-dcf2-11e8-9c26-deeaffe0dc35.png)
![screen shot 2018-10-31 at 9 50 14 am](https://user-images.githubusercontent.com/7063154/47792447-718c0c00-dcf2-11e8-8e73-bfb8dea57d42.png)

![Uploading Screen Shot 2018-10-31 at 9.50.31 AM.png…]()

**Comment by bradfordcondon** [comment]
https://github.com/tripal/tripal/issues/100

**Comment by bradfordcondon** [comment]
I'm going to start with a "general all child feature" field, specific for gene, and go from there.  The term i'll use is data:0916 from EDAM: "Gene report" . 

https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_0916

there's also nucleic acid report (https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_2084) ifw e want to make it more feature agnostic.

**Comment by bradfordcondon** [comment]
Here's my first step.
Next step is to provide a clickable popup element for the sequences

<img width="655" alt="screen shot 2018-11-05 at 3 11 21 pm" src="https://user-images.githubusercontent.com/7063154/48023893-12246680-e10d-11e8-927d-e2b9301799e2.png">

I'm torn on if the popup should just be for sequence, or if it should have ALL extra information, including the featureloc (start, stop, strand) and the annotation definitions (right now the annotation field is just a list of annotation names.  I need to load some example data so that it shows up here.....

**Comment by mpoelchau** [comment]
@bradfordcondon would there be a way to tie the sequence retrieval into the Tripal collections module somehow?

We currently only have functionality for users to copy/paste from the popup. Ideally though they'd be able to download as fasta. Or both.

**Comment by bradfordcondon** [comment]
I've added a very simple popup window for each sequence.

I loaded the apis set @mpoelchau provided me with.  here are the two genes:

![screen shot 2018-11-06 at 11 33 21 am](https://user-images.githubusercontent.com/7063154/48078656-e27e6880-e1b7-11e8-8396-c42961fd2444.png)


![screen shot 2018-11-06 at 11 33 05 am](https://user-images.githubusercontent.com/7063154/48078661-e5795900-e1b7-11e8-9c36-78db06ae3c28.png)


Conclusions I draw:

We want to infer the sequence for each child feature if it doesnt have on directly associated (right?)
If yes, then thats simple for some features, and we need to be cautious for others (CDS comes to mind... any others?  My biology is rusty...)

The fact that the parent table is the top one, and the children table is the bottom, isnt clear at all.  Let's maybe reformat the first one to just be two columns, key and value?  And add the name, uniquename, etc, to make it more clear?


Additional:  We need to link out to feature pages if they exist by checking if the entity exists.

**Comment by bradfordcondon** [comment]
Rather than try to cram all of the child feature info into a single field, the approach taken will be to 

a) create a master index field which follows tripal web services best practice and has all the info needed for child features,

b) have other fields check that that field has loaded.  Once it has, pull in the info they need.

The master field has a draft done: i put the code in my catch-all module for now: https://github.com/statonlab/tripal_manage_analyses/tree/gene_field

It stores an object looking like this in its . value:
```
[feature_id of first child] => [ info => ['array_of_info'], children => ['array_of_children keyed by feature_id']]
```

As you can see each node of the array has info describing that feature, and children which is a list of feature children associated with that feature.    At each node, in info, we've crammed in all hte stuff we're going to want to pass along to other fields.  This includes:

- the sequence, for display in the sequence field
- feature_cvterms for display in hte annotation field
- props for display in a new, to-bewritten, childprop field (since each property is its own field in tripal 3, there isnt one field htat summarizes them we can stick our code into).

Now that the base index field is taken care of, I'll work on the childprop field.

**Comment by bradfordcondon** [comment]
Here's the child properties field in action:

![screen shot 2018-12-19 at 11 38 19 am](https://user-images.githubusercontent.com/7063154/50233973-9ca1ec00-0382-11e9-8dab-0b0bc6eac511.png)

we're on a gene page (FRAEX38873_v2_000001410).   each mRNA (FRAEX38873_v2_000001410.1 & 2) has a collapsible fieldset with a table inside listing any featureprops associated with the mRNA or any child of the mRNA or any children of that child ie   FRAEX38873_v2_000001410.2.cds3.

I'll follow this general design pattern for the other alternate fields: so the new annotations field, for example, will similarly be broken down into collapsible fieldsets by mRNA.  We do this to keep the information manageable-- we expect different isoforms of the same transcript to have many of the same annotations.

**Comment by bradfordcondon** [comment]
I opened a PR into core https://github.com/tripal/tripal/pull/837

We have athree fields:

the base field that stores all info.  It also maps out the feature:

![image](https://user-images.githubusercontent.com/7063154/51839689-eb269c80-22d7-11e9-92e4-c6e06668c91b.png)

- a feature property field (featureprop)

![image](https://user-images.githubusercontent.com/7063154/51839729-0d201f00-22d8-11e9-8b66-0aa840a65375.png)


- a feature annotation field (feature_cvterm)


There are some outstanding issues im working on.

I think as far as I5K is concerned, whats really missing is a nice way of displaying all the sequence information.

**Comment by bradfordcondon** [comment]
a note on collapsible fieldsets- I just merged a pr that [makes them compatible with i5k's theme](https://github.com/statonlab/tripal_manage_analyses/pull/68).

**Comment by bradfordcondon** [comment]
OK, this isnt amazing but it does work on all themes which was the trick-   We now have a sequence column.   Clicking on the word sequence expands it, clicking again hides it.

We use the `chado_get_feature_sequences` API which in theory (but not in practice for i5k data i've tested) should find sequenced derived from mapped sequences.


![Screen Shot 2019-03-25 at 1 25 11 PM](https://user-images.githubusercontent.com/7063154/54940706-abf48080-4f01-11e9-9a74-ea5346e1b058.png)

![Screen Shot 2019-03-25 at 1 25 17 PM](https://user-images.githubusercontent.com/7063154/54940808-d9d9c500-4f01-11e9-91a8-a62269f5a506.png)

**Comment by mpoelchau** [comment]
Great discussion here but in the interim we're using the vanilla tripal gene pages. We'll resume the discussion on gene pages at a later date.
