### ISSUE TITLE
Workflow: wget -> check_checksum

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/general_issues#6]
code available in **demo_workflow5**

wget -> check_checksum

```
wget <url1> <url2> <url3> ...... <urlN>
```

```
md5sum -c md5checksums.txt &> check.log
```

- About capturing stdout or stderr
To capture a stderr, the stderr section can only be supported in {class: CommandLineTool}, not in {class:Workflow}.

**Comment by mpoelchau** [comment]
@r06942072  - can this issue be closed?
