### ISSUE TITLE
GFF annotations are not where tripal expects

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/general_issues#8]
when working on #5 we found that i5k sotres feature annotations loaded via gFF in featureprop.

However, tripal stores annotations in feature_cvterm, at least, when they are loaded via the direct annotation importers (tripal_analysis_interpro, tripal_analysis_kegg, tripal_analysis_go).

Furthermore, tripal does indeed try to load annotations into feature_cvterm, but only if they are with the Ontology_term attribute.  see:
https://github.com/tripal/tripal/blob/a2f3c1e3414011adfced99e98b15365326904792/tripal_chado/includes/TripalImporter/GFF3Importer.inc#L1432

One good reason/argument for storing annotations in feature_cvterm is the existence of the feature_cvtermprop table, which is designed to store *evidence codes* for annotations.  You can see the chado table description [makes this clear](https://laceysanderson.github.io/chado-docs/tables/feature_cvtermprop.html)

Let's

a) look at our GFF and see what the annotations look like
b) consider counterarguments to the points i lay out above.  I wouldnt be surprised if theres documentation out there supporting annotations in featureprop instead.
b) think about if we would want to convert
c) think about if Tripal's GFF importer should be smarter in how it searches annotations
d) look at what generates the GFF and if it should be printing the tags differently

**Comment by mpoelchau** [comment]
See also https://github.com/GMOD/Chado/issues/74

I've updated our gff loading documentation to specify loading GO, Kegg and InterPro as both Ontology_term and Dbxref attributes. (The latter because 1) our current Tripal2 gene pages still expect them in featureprop, and 2) there is no obo file for InterPro so technically Tripal can't add these to feature_cvterm)

**Comment by bradfordcondon** [comment]
>there is no obo file for InterPro so technically Tripal can't add these to feature_cvterm

Tripal inserts the InterPro terms it encounters into chado.cvterm when loading Interpro results.

see:

https://github.com/tripal/tripal_analysis_interpro/blob/dc70e60775b41790d30d46fe574c2cf63e05ebcc/includes/TripalImporter/InterProImporter.inc#L585-L594

**Comment by mpoelchau** [comment]
Right - but the tripal interpro importer works only IPRscan xml files, right (not with gff)? Unfortunately we don't always have these. We could certainly ask users to submit these along with gffs if they have them.

**Comment by bradfordcondon** [comment]
yes thats definitely true.  With a little work you could simply download the altest IPR defintions and batch-load them in non-OBO form (since IPR has almost no relationships anyway)
